"""``tripl codegen`` customisation: a team's own tracking shape from custom templates.

The fixture ``tests/codegen/custom/`` (a synthetic plan, ``check.yml`` and the
templates under ``templates/``) rebuilds, with NO dedicated switch, the shapes
a team may already have in its code base:

(a) constant holders instead of enums (``object AcmeCategory { const val … }``),
    for Kotlin and TypeScript one file per plan field (``codegen.files`` with
    ``each: closed_fields``), for Swift in the event type's own file;
(b) a structured event built as the team's own ``AcmeEvent`` value and handed
    on, with Snowplow's numeric ``value`` mapped to the ``value:number`` role;
(c) screen views as one enum of the PLANNED (type, id) pairs (``plan.combinations``);
(d) event-name and property-key constants (``plan.events``, ``plan.fields``).

Goldens live in ``tests/codegen/custom/golden/<lang>/``; regenerate them with
``TRIPL_UPDATE_GOLDEN=1`` after an intended change and review the diff.
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path

import pytest

from tripl_cli.check import yamlish
from tripl_cli.check.config import load, parse
from tripl_cli.cli import main
from tripl_cli.codegen.files import sync
from tripl_cli.codegen.generate import GeneratedFile, generate
from tripl_cli.codegen.model import CodegenModel, parse_model
from tripl_cli.codegen.naming import NameScope, name_forms
from tripl_cli.errors import TriplConfigError

FIXTURES = Path(__file__).parent / "codegen"
CUSTOM = FIXTURES / "custom"
GOLDEN = CUSTOM / "golden"
PROJECT = "acme"


def _model(path: Path = CUSTOM / "model.json") -> CodegenModel:
    return parse_model(json.loads(path.read_text(encoding="utf-8")))


def _generate(out: Path) -> list[GeneratedFile]:
    return generate(load(CUSTOM / "check.yml"), _model(), PROJECT, out=out)


def _by_name(files: list[GeneratedFile]) -> dict[str, str]:
    return {f"{item.language}/{item.path.name}": item.content for item in files}


def _parse(text: str, base: Path) -> object:
    return parse(yamlish.loads(text), path=None, base=base)


def _generate_text(
    config_text: str, base: Path, model: CodegenModel | None = None
) -> dict[str, str]:
    config = parse(yamlish.loads(config_text), path=None, base=base)
    files = generate(config, model or _model(FIXTURES / "model.json"), "demo", out=base / "out")
    return _by_name(files)


# --- golden ------------------------------------------------------------------------
def test_custom_templates_match_their_golden_files(tmp_path: Path) -> None:
    produced = _by_name(_generate(tmp_path))
    if os.environ.get("TRIPL_UPDATE_GOLDEN"):
        for relative, content in produced.items():
            target = GOLDEN / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content.encode("utf-8"))
    expected = {
        path.relative_to(GOLDEN).as_posix(): path.read_bytes().decode("utf-8")
        for path in sorted(GOLDEN.rglob("*"))
        if path.is_file()
    }
    assert sorted(produced) == sorted(expected)
    for relative, content in produced.items():
        assert content == expected[relative], f"{relative} differs from its golden file"


def test_every_extra_file_carries_the_header(tmp_path: Path) -> None:
    for item in _generate(tmp_path):
        lines = item.content.splitlines()
        assert lines[0] == "// Generated by tripl codegen — do not edit."
        assert lines[1] == "// Plan: project acme, branch main, plan a1b2c3d4e5f6."


# --- (a) constant holders ----------------------------------------------------------
def test_one_holder_file_per_closed_field(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    for language, names in (
        ("kotlin", ["AcmeAction.kt", "AcmeCategory.kt", "AcmeLabel.kt", "AcmeProperty.kt"]),
        ("ts", ["acmeAction.ts", "acmeCategory.ts", "acmeLabel.ts", "acmeProperty.ts"]),
    ):
        for name in names:
            assert f"{language}/{name}" in files
    assert 'const val Checkout = "checkout"' in files["kotlin/AcmeCategory.kt"]
    assert "object AcmeCategory {" in files["kotlin/AcmeCategory.kt"]
    assert "export const AcmeCategory = {\n  checkout: 'checkout'," in files["ts/acmeCategory.ts"]
    swift = files["swift/AcmeStructured.swift"]
    assert 'public enum AcmeCategory {\n    public static let checkout = "checkout"' in swift
    # A value backed by a variable with allowed values is a planned value too.
    assert 'const val Show = "show"' in files["kotlin/AcmeAction.kt"]


def test_names_are_escaped_for_each_language_and_collisions_numbered(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    label_kt, label_ts = files["kotlin/AcmeLabel.kt"], files["ts/acmeLabel.ts"]
    swift = files["swift/AcmeStructured.swift"]
    # Digit first, a reserved word, and two values landing on one name.
    assert 'const val _1stCard = "1st_card"' in label_kt
    assert 'public static let default_ = "default"' in swift
    assert "  default_: 'default'," in label_ts
    assert 'const val PromoSheet = "promo-sheet"' in label_kt
    assert 'const val PromoSheet2 = "promo_sheet"' in label_kt
    assert 'public static let class_ = "class"' in swift
    # Cross-file references use the SAME names the holders declared.
    planned = files["swift/AcmePlanned.swift"]
    assert "label: AcmeLabel.promoSheet), // deprecated" in planned
    assert "label: AcmeLabel.promoSheet2)," in planned
    assert "property: AcmeProperty.class_)" in planned


def test_name_forms_per_language() -> None:
    assert name_forms("Home Screen View", "kotlin") == {
        "upper_snake": "HOME_SCREEN_VIEW",
        "lower_snake": "home_screen_view",
        "camel": "homeScreenView",
        "pascal": "HomeScreenView",
    }
    assert name_forms("class", "swift")["camel"] == "class_"
    assert name_forms("class", "swift")["lower_snake"] == "class_"
    assert name_forms("default", "ts")["camel"] == "default_"
    assert name_forms("string", "swift")["pascal"] == "StringValue"
    assert name_forms("1st run", "kotlin")["upper_snake"] == "_1ST_RUN"
    assert name_forms("!!!", "ts")["camel"] == "value"
    scope = NameScope("kotlin")
    first, second = scope.take("promo_sheet"), scope.take("promo-sheet")
    assert first["camel"] == "promoSheet" and second["camel"] == "promoSheet2"
    # Every form of one item carries the same suffix.
    assert second == {
        "upper_snake": "PROMO_SHEET2",
        "lower_snake": "promo_sheet2",
        "camel": "promoSheet2",
        "pascal": "PromoSheet2",
    }


# --- (b) the team's own value object -------------------------------------------------
def test_structured_event_is_built_as_the_teams_value_object(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    kotlin = files["kotlin/AcmeStructured.kt"]
    assert "        value: Double? = null\n    ): AcmeEvent = AcmeEvent(" in kotlin
    assert "        property = property,\n        value = value\n    )" in kotlin
    swift = files["swift/AcmeStructured.swift"]
    assert "        value: Double? = nil\n    ) -> AcmeEvent {" in swift
    ts = files["ts/acmeStructured.ts"]
    assert (
        "  label?: AcmeLabel,\n  property?: AcmeProperty,\n  value?: number,\n): AcmeEvent {"
    ) in ts
    assert "import type { AcmeLabel } from './acmeLabel';" in ts


@pytest.mark.parametrize(
    ("name", "signature", "forward"),
    [
        (
            "kotlin/SeTracking.kt",
            "fun log(category: Category, action: Action, label: String? = null, "
            "value: Double? = null)",
            "Tracker.log(category = category.value, action = action.value, label = label, "
            "value = value)",
        ),
        (
            "swift/SeTracking.swift",
            "public static func log(category: Category, action: Action, label: String? = nil, "
            "value: Double? = nil)",
            "Tracker.log(category: category.rawValue, action: action.rawValue, label: label, "
            "value: value)",
        ),
        (
            "ts/seTracking.ts",
            "export function log(category: Category, action: Action, label?: string, "
            "value?: number): void",
            "tracker.log(category, action, label, value);",
        ),
    ],
)
def test_value_role_is_an_optional_number_forwarded_as_is(
    tmp_path: Path, name: str, signature: str, forward: str
) -> None:
    args = "{category: category, action: action, label: label, value: 'value:number'}"
    files = _generate_text(
        f"""
event_types:
  se:
    codegen:
      style: structured
      transport:
        swift: {{function: "Tracker.log", args: {args}}}
        kotlin: {{function: "Tracker.log", args: {args}}}
        ts: {{function: "tracker.log", positional: [category, action, label, "value:number"]}}
""",
        tmp_path,
    )
    assert signature in files[name]
    assert forward in files[name]


def test_value_role_is_refused_for_the_named_styles(tmp_path: Path) -> None:
    config = """
event_types:
  legacy:
    codegen:
      style: named
      languages: [kotlin]
      transport: {kotlin: {function: "Tracker.log", positional: [name, "value:number"]}}
"""
    with pytest.raises(TriplConfigError, match="value:number"):
        _generate_text(config, tmp_path)


def test_value_role_is_ignored_by_tripl_check() -> None:
    from tripl_cli.check.config import VALUE_NUMBER
    from tripl_cli.check.scan import _assign, _Collected
    from tripl_cli.check.values import Value

    collected = _Collected(fields={})
    _assign(collected, VALUE_NUMBER, Value("text", text="4.5"))
    assert collected.fields == {}


# --- (c) planned (type, id) pairs ---------------------------------------------------
def test_screens_are_the_planned_pairs_only(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    kotlin = files["kotlin/AcmeScreens.kt"]
    assert 'CHECKOUT_CART("checkout", "cart"),' in kotlin
    # A variable-backed id is expanded into one pair per allowed value.
    assert 'PAYWALL_ANNUAL("paywall", "annual"),' in kotlin
    assert 'PAYWALL_MONTHLY("paywall", "monthly"),' in kotlin
    # A screen without an id.
    assert 'SETTINGS("settings", null);' in kotlin
    assert "AcmeTracker.trackScreen(type = screen.type, id = screen.id)" in kotlin
    assert "        case .settings: return nil" in files["swift/AcmeScreens.swift"]
    assert "  settings: { type: 'settings', id: null }," in files["ts/acmeScreens.ts"]


# --- (d) name and key constants -------------------------------------------------------
def test_event_name_and_property_key_constants(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    kotlin = files["kotlin/AcmeAppConstants.kt"]
    # The event type's own `vars` win over the top-level ones (prefix AcmeApp, not Acme).
    assert "object AcmeAppEventNames {" in kotlin
    assert 'const val CHECKOUT_STARTED = "checkout_started"' in kotlin
    deprecated = '@Deprecated("Deprecated in the tracking plan.")\n'
    assert deprecated + '    const val CLASS = "class"' in kotlin
    assert (
        'fun promoPromoCodeApplied(promoCode: String): String = "promo_${promoCode}_applied"'
        in kotlin
    )
    assert 'const val PLAN_TIER = "plan_tier"' in kotlin
    swift = files["swift/AcmeAppConstants.swift"]
    assert 'public static let class_ = "class"' in swift
    assert '-> String { "promo_\\(promoCode)_applied" }' in swift
    ts = files["ts/acmeAppConstants.ts"]
    assert "  planTier: 'plan_tier'," in ts


# --- vars ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    ("block", "message"),
    [
        ("vars: {prefix: 1}", r"vars\.prefix: expected a string, got int"),
        ("vars: {prefix: true}", r"vars\.prefix: expected a string, got bool"),
        ("vars: {prefix: [a]}", r"vars\.prefix: expected a string, got list"),
        ("vars: {prefix: {a: b}}", r"vars\.prefix: expected a string, got dict"),
        ("vars: {'my-prefix': Acme}", r"'my-prefix' is not a variable name"),
        ("vars: [prefix]", r"vars: expected a mapping"),
    ],
)
def test_vars_must_be_a_flat_map_of_strings(tmp_path: Path, block: str, message: str) -> None:
    with pytest.raises(TriplConfigError, match=message):
        _parse(f"event_types:\n  se:\n    codegen:\n      {block}\n", tmp_path)
    with pytest.raises(TriplConfigError, match=message):
        _parse(f"codegen:\n  {block}\nevent_types:\n  se: {{codegen: {{}}}}\n", tmp_path)


def test_a_missing_var_is_a_template_error(tmp_path: Path) -> None:
    template = tmp_path / "t.mustache"
    template.write_text("{{header}}\n{{vars.missing}}\n", encoding="utf-8")
    config = f"""
event_types:
  se:
    codegen:
      languages: [kotlin]
      template: {template}
"""
    with pytest.raises(TriplConfigError, match=r"unknown value \{\{vars\.missing\}\}"):
        _generate_text(config, tmp_path)


# --- files ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    ("entries", "message"),
    [
        ("[{language: kotlin, template: t.mustache, file: ../Escape.kt}]", "without a directory"),
        ("[{language: kotlin, template: t.mustache, file: sub/Holder.kt}]", "without a directory"),
        ("[{language: kotlin, template: t.mustache, file: 'C:Holder.kt'}]", "without a directory"),
        ("[{language: kotlin, template: t.mustache, file: .Holder.kt}]", "must not start with"),
        ("[{language: kotlin, template: t.mustache, file: Holder.swift}]", r"must end in \.kt"),
        ("[{language: swift, template: t.mustache, file: Holder.kt}]", r"must end in \.swift"),
        ("[{language: ts, template: t.mustache, file: holder.tsx}]", r"must end in \.ts"),
        (
            "[{language: kotlin, template: t.mustache, file: Holder.kt},"
            " {language: kotlin, template: t.mustache, file: holder.kt}]",
            "already written by files",
        ),
        (
            "[{language: kotlin, template: t.mustache, file: Holder.kt, each: fields}]",
            r"needs a \{\{…\}\} tag",
        ),
        (
            "[{language: kotlin, template: t.mustache, file: '{{names.pascal}}.kt', each: x}]",
            "is not one of fields, closed_fields, events",
        ),
        ("[{language: kotlin, file: Holder.kt}]", "needs `template:`"),
        ("[{language: kotlin, template: t.mustache, file: H.kt, extra: 1}]", "unknown key"),
    ],
)
def test_files_entries_are_validated(tmp_path: Path, entries: str, message: str) -> None:
    with pytest.raises(TriplConfigError, match=message):
        _parse(f"event_types:\n  se:\n    codegen:\n      files: {entries}\n", tmp_path)


def _files_config(tmp_path: Path, template_text: str, file: str, extra: str = "") -> str:
    template = tmp_path / "extra.mustache"
    template.write_text(template_text, encoding="utf-8")
    return f"""
event_types:
  se:
    codegen:
      languages: [kotlin]
      {extra}
      files: [{{language: kotlin, template: {template}, file: "{file}"}}]
"""


def test_a_rendered_file_name_cannot_leave_the_directory(tmp_path: Path) -> None:
    config = _files_config(
        tmp_path, "{{header}}\n", "{{vars.dir}}Holder.kt", extra="vars: {dir: '../'}"
    )
    with pytest.raises(TriplConfigError, match="without a directory"):
        _generate_text(config, tmp_path)


def test_an_extra_file_must_start_with_the_header(tmp_path: Path) -> None:
    config = _files_config(tmp_path, "object Holder\n", "Holder.kt")
    with pytest.raises(TriplConfigError, match=r"must start with \{\{header\}\}"):
        _generate_text(config, tmp_path)


def test_an_extra_file_cannot_take_the_event_types_own_file(tmp_path: Path) -> None:
    config = _files_config(tmp_path, "{{header}}\n", "SeTracking.kt")
    with pytest.raises(TriplConfigError, match="twice"):
        _generate_text(config, tmp_path)


def test_an_extra_file_needs_one_of_the_event_types_languages(tmp_path: Path) -> None:
    template = tmp_path / "extra.mustache"
    template.write_text("{{header}}\n", encoding="utf-8")
    config = f"""
event_types:
  se:
    codegen:
      languages: [kotlin]
      files: [{{language: swift, template: {template}, file: Holder.swift}}]
"""
    with pytest.raises(TriplConfigError, match="not one of this event type's languages"):
        _generate_text(config, tmp_path)


def test_lang_skips_the_extra_files_of_other_languages(tmp_path: Path) -> None:
    files = generate(
        load(CUSTOM / "check.yml"), _model(), PROJECT, languages=["swift"], out=tmp_path
    )
    names = sorted(item.path.name for item in files)
    assert "AcmePlanned.swift" in names
    assert not [name for name in names if not name.endswith(".swift")]


def test_check_sees_extra_files_and_cleanup_keeps_them(tmp_path: Path) -> None:
    files = _generate(tmp_path)
    extras = [tmp_path / "kotlin" / "AcmeCategory.kt", tmp_path / "swift" / "AcmePlanned.swift"]
    assert all(item in {f.path for f in files} for item in extras)

    first = sync(files, check=False, project=PROJECT)
    assert all(path.exists() for path in extras)
    assert set(extras) <= set(first.created)

    # A second write leaves every extra file in place: none of them is "stale".
    again = sync(_generate(tmp_path), check=False, project=PROJECT)
    assert not again.stale and not again.drifted
    assert all(path.exists() for path in extras)

    # --check reports a missing or edited extra file, and writes nothing.
    extras[0].unlink()
    extras[1].write_text(extras[1].read_text(encoding="utf-8") + "// edit\n", encoding="utf-8")
    checked = sync(_generate(tmp_path), check=True, project=PROJECT)
    assert extras[0] in checked.created and extras[1] in checked.changed
    assert checked.drifted and not extras[0].exists()

    # An extra file the config no longer produces is ours and stale: removed on a write.
    retired = tmp_path / "kotlin" / "AcmeRetired.kt"
    shutil.copy(tmp_path / "kotlin" / "AcmeLabel.kt", retired)
    result = sync(_generate(tmp_path), check=False, project=PROJECT)
    assert result.stale == [retired] and not retired.exists()
    assert all(path.exists() for path in extras)


def test_codegen_command_writes_and_checks_the_extra_files(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    root = tmp_path / "repo"
    (root / ".tripl").mkdir(parents=True)
    (root / ".git").mkdir()
    shutil.copy(CUSTOM / "check.yml", root / ".tripl" / "check.yml")
    shutil.copytree(CUSTOM / "templates", root / "templates")
    shutil.copy(CUSTOM / "model.json", root / "model.json")
    monkeypatch.chdir(root)

    assert main(["codegen", "--model", "model.json"]) == 0
    written = root / "generated" / "kotlin" / "AcmeCategory.kt"
    assert written.read_bytes() == (GOLDEN / "kotlin" / "AcmeCategory.kt").read_bytes()
    assert main(["codegen", "--model", "model.json", "--check"]) == 0

    written.unlink()
    capsys.readouterr()
    assert main(["codegen", "--model", "model.json", "--check"]) == 1
    captured = capsys.readouterr()
    assert "generated/kotlin/AcmeCategory.kt" in captured.out + captured.err


# --- the context ---------------------------------------------------------------------
def test_new_context_keys_are_additive(tmp_path: Path) -> None:
    from tripl_cli.check.config import load as load_config
    from tripl_cli.codegen.context import Target
    from tripl_cli.codegen.generate import target_context

    config = load_config(CUSTOM / "check.yml")
    spec = next(item for item in config.event_types if item.name == "screen")
    model = _model()
    event_type = model.event_type("screen")
    assert spec.codegen is not None and event_type is not None
    target = Target(spec, spec.codegen, event_type, model, PROJECT, vars=config.codegen.vars)
    context = target_context(target, "kotlin")
    for key in ("header", "namespace", "enums", "function", "known", "imports", "event_type"):
        assert key in context
    assert context["vars"]["prefix"] == "Acme"
    plan = context["plan"]
    assert [field["raw"] for field in plan["fields"]] == ["type", "id"]
    assert plan["field"]["type"]["closed"] is True
    assert [value["raw"] for value in plan["field"]["id"]["values"]] == [
        "annual",
        "cart",
        "confirm",
        "main",
        "monthly",
    ]
    paywall = next(event for event in plan["events"] if event["dynamic"])
    assert paywall["value"]["id"]["dynamic"] is True
    assert paywall["tokens"][0]["names"]["camel"] == "paywallPlan"
    assert [item["raw"] for item in plan["combinations"]][-3:] == [
        "Paywall annual",
        "Paywall monthly",
        "Settings",
    ]
    transport = context["transport"]
    assert transport["function"] == "AcmeTracker.trackScreen"
    assert [(arg["label"], arg["role"], arg["param"]) for arg in transport["args"]] == [
        ("type", "field", "type"),
        ("id", "field", "id"),
    ]
    assert context["enums"][0]["cases"][0]["names"]["upper_snake"] == "CHECKOUT"
    assert [param["role"] for param in context["function"]["params"]] == ["field", "field"]


# --- one naming scope for the fields ------------------------------------------------
# Two fields that land on one name, and a plan field called `value` next to the
# numeric `value:number` role.
_COLLIDING_MODEL = {
    "format": "codegen_model",
    "revision": "r",
    "branch": "main",
    "plan_hash": "a1b2c3d4e5f6",
    "variables": [],
    "event_types": [
        {
            "name": "se",
            "display_name": "S",
            "name_rule": "{a-b}:{a_b}",
            "fields": [
                {
                    "name": name,
                    "required": name == "a-b",
                    "type": "string",
                    "values": None,
                    "variable": None,
                }
                for name in ("a-b", "a_b", "value", "default")
            ],
            "events": [
                {
                    "identity": "x:y",
                    "name": "x:y",
                    "status": "active",
                    "field_values": {"a-b": "x", "a_b": "y", "default": "z"},
                    "deprecated": False,
                }
            ],
        }
    ],
}
_FIELD_NAMES = "{{#is_field}}{{target}}={{names.camel}} {{/is_field}}"
_COLLIDING_TEMPLATE = (
    "{{header}}\n"
    "fields: {{#plan.fields}}{{names.camel}} {{/plan.fields}}\n"
    f"params: {{{{#function.params}}}}{_FIELD_NAMES}{{{{/function.params}}}}\n"
    f"args: {{{{#transport.args}}}}{_FIELD_NAMES}{{{{/transport.args}}}}\n"
    "keys: {{plan.field.a_b.raw}} {{plan.field.default.raw}} "
    "{{#plan.events}}{{value.default.raw}}{{/plan.events}}\n"
)


def _colliding(tmp_path: Path, template_text: str, language: str) -> str:
    template = tmp_path / "t.mustache"
    template.write_text(template_text, encoding="utf-8")
    model_path = tmp_path / "model.json"
    model_path.write_text(json.dumps(_COLLIDING_MODEL), encoding="utf-8")
    args = "{n: name, a: 'a-b', b: 'a_b', v: 'value:number', f: 'field:value'}"
    transport = (
        "{function: t.send, positional: [name, 'a-b', 'a_b', 'value:number', 'field:value']}"
        if language == "ts"
        else f"{{function: T.send, args: {args}}}"
    )
    config = f"""
event_types:
  se:
    codegen:
      style: structured
      languages: [{language}]
      transport: {{{language}: {transport}}}
      template: {{{language}: {template}}}
"""
    files = _generate_text(config, tmp_path, _model(model_path))
    return next(content for name, content in files.items() if "Tracking" in name)


@pytest.mark.parametrize("language", ["kotlin", "swift", "ts"])
def test_a_field_has_the_same_names_in_plan_params_and_transport_args(
    tmp_path: Path, language: str
) -> None:
    lines = _colliding(tmp_path, _COLLIDING_TEMPLATE, language).splitlines()[3:]
    default = "default" if language == "kotlin" else "default_"
    assert lines[0] == f"fields: aB aB2 {default} value "
    assert lines[1] == "params: a-b=aB a_b=aB2 value=value "
    assert lines[2] == "args: a-b=aB a_b=aB2 value=value "
    # `plan.field` and `value.` are keyed by the plain name, the same in every language;
    # of `a-b` and `a_b` (both `a_b`) the first field keeps the key.
    assert lines[3] == "keys: a-b default z"


@pytest.mark.parametrize(
    ("language", "tag"),
    [
        ("kotlin", "{{#transport.args}}{{label}} = {{param}}{{/transport.args}}"),
        ("ts", "{{#transport.args}}{{label}}{{/transport.args}}"),
        ("kotlin", "{{#function.params}}{{names.camel}}{{/function.params}}"),
        ("kotlin", "{{#plan.fields}}{{variable}}{{/plan.fields}}"),
    ],
)
def test_a_key_with_no_value_is_an_error_not_a_hole(
    tmp_path: Path, language: str, tag: str
) -> None:
    with pytest.raises(TriplConfigError, match="unknown value"):
        _colliding(tmp_path, "{{header}}\n" + tag + "\n", language)


def test_a_key_with_no_value_still_works_as_a_guard(tmp_path: Path) -> None:
    text = _colliding(
        tmp_path,
        "{{header}}\n{{#transport.args}}[{{#label}}{{label}}{{/label}}"
        "|{{#param}}{{param}}{{/param}}{{^param}}-{{/param}}]{{/transport.args}}"
        "{{^transport.import}} no-import{{/transport.import}}\n",
        "kotlin",
    )
    assert text.splitlines()[3] == "[n|-][a|aB][b|aB2][v|value][f|value_] no-import"


def test_camel_names_avoid_swifts_synthesized_members() -> None:
    assert name_forms("all cases", "swift")["camel"] == "allCases_"
    assert name_forms("raw value", "swift")["camel"] == "rawValue_"
    assert name_forms("hash value", "swift")["camel"] == "hashValue_"
    assert name_forms("all cases", "kotlin")["camel"] == "allCases"


# --- the value role in `calls` --------------------------------------------------------
_CALLS_ONLY = """
event_types:
  se:
    calls:
      - function: "Tracker.log"
        args: {category: category, action: action, value: "value:number"}
    codegen:
      style: structured
      languages: [kotlin]
"""


def test_value_role_in_calls_alone_is_not_forwarded(tmp_path: Path) -> None:
    # Without a `transport` the code forwards to TriplDestination, which has no numeric value.
    kotlin = _generate_text(_CALLS_ONLY, tmp_path)["kotlin/SeTracking.kt"]
    assert "Double" not in kotlin


def test_value_role_in_calls_is_forwarded_by_a_bare_function_transport(tmp_path: Path) -> None:
    config = _CALLS_ONLY + '      transport: {kotlin: "Tracker.log"}\n'
    kotlin = _generate_text(config, tmp_path)["kotlin/SeTracking.kt"]
    assert "value: Double? = null" in kotlin
    assert "value = value)" in kotlin


# --- file names -----------------------------------------------------------------------
@pytest.mark.parametrize("value", ["a b", "a\\nb", "a*b", "a?b", "é"])
def test_a_rendered_file_name_must_be_plain(tmp_path: Path, value: str) -> None:
    config = _files_config(
        tmp_path, "{{header}}\n", "{{vars.p}}Holder.kt", extra=f'vars: {{p: "{value}"}}'
    )
    with pytest.raises(TriplConfigError, match="is not a plain file name"):
        _generate_text(config, tmp_path)


def test_an_extra_file_cannot_take_the_shared_transport_file(tmp_path: Path) -> None:
    config = _files_config(tmp_path, "{{header}}\n", "tripltransport.kt")
    with pytest.raises(
        TriplConfigError,
        match=r"TriplTransport\.kt is the shared transport file; give the `files` entry "
        r"of event type 'se' another name",
    ):
        _generate_text(config, tmp_path)
