"""``tripl codegen`` generation: golden files per style x language, and the rules behind them.

The fixture (``tests/codegen/model.json`` + ``check.yml``) is a synthetic plan
with one event type per style: ``se`` (structured, through the team wrapper),
``screen`` (screen_view, through the shared destination), ``legacy`` (named)
and ``sd`` (self-describing). Its values are chosen to hit the naming edge
cases: a digit-first value, a reserved word, a variable-backed value, a free
``${token}``, spaces and colons in event names, deprecated and archived events.

Golden files live in ``tests/codegen/golden/<lang>/``. After an intended
change, regenerate them with ``TRIPL_UPDATE_GOLDEN=1`` and review the diff.

No Swift, Kotlin or TypeScript compiler runs here (the CLI test environment has
none; see ``test_generated_typescript_compiles`` for the opt-in TS check), so
the generated code's shape is asserted structurally instead.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

from tripl_cli.check.config import load, parse
from tripl_cli.codegen.generate import GeneratedFile, generate
from tripl_cli.codegen.languages import kotlin_string, swift_string, ts_string
from tripl_cli.codegen.model import CodegenModel, parse_model
from tripl_cli.errors import TriplConfigError, TriplError

FIXTURES = Path(__file__).parent / "codegen"
GOLDEN = FIXTURES / "golden"
REVISION = "9b1f0c52-5d0e-4d6a-8a31-2f6c0e7d4a42"
PLAN_HASH = "5e0d4c3b2a19"


def _model() -> CodegenModel:
    return parse_model(json.loads((FIXTURES / "model.json").read_text(encoding="utf-8")))


def _generate(out: Path, config_text: str | None = None, **kwargs: object) -> list[GeneratedFile]:
    if config_text is None:
        config = load(FIXTURES / "check.yml")
    else:
        from tripl_cli.check import yamlish

        config = parse(yamlish.loads(config_text), path=None, base=out)
    return generate(config, _model(), "demo", out=out, **kwargs)  # type: ignore[arg-type]


def _by_name(files: list[GeneratedFile]) -> dict[str, str]:
    return {f"{item.language}/{item.path.name}": item.content for item in files}


# --- golden ------------------------------------------------------------------------
def test_every_style_in_every_language_matches_its_golden_file(tmp_path: Path) -> None:
    files = _generate(tmp_path)
    produced = {f"{item.language}/{item.path.name}": item.content for item in files}
    if os.environ.get("TRIPL_UPDATE_GOLDEN"):
        for relative, content in produced.items():
            target = GOLDEN / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content.encode("utf-8"))
    expected = {
        path.relative_to(GOLDEN).as_posix(): path.read_bytes().decode("utf-8")
        for path in sorted(GOLDEN.rglob("*"))
        if path.is_file()
    }
    assert sorted(produced) == sorted(expected)
    # 4 styles x 3 languages, plus one shared transport file per language.
    assert len(produced) == 15
    for relative, content in produced.items():
        assert content == expected[relative], f"{relative} differs from its golden file"


def test_output_is_deterministic_and_independent_of_server_order(tmp_path: Path) -> None:
    raw = json.loads((FIXTURES / "model.json").read_text(encoding="utf-8"))
    for event_type in raw["event_types"]:
        event_type["events"].reverse()
        event_type["fields"].reverse()
    raw["event_types"].reverse()
    raw["variables"].reverse()
    config = load(FIXTURES / "check.yml")
    shuffled = generate(config, parse_model(raw), "demo", out=tmp_path)
    assert [item.content for item in shuffled] == [item.content for item in _generate(tmp_path)]


def test_every_file_carries_the_do_not_edit_header(tmp_path: Path) -> None:
    for item in _generate(tmp_path):
        lines = item.content.splitlines()
        assert lines[0] == "// Generated by tripl codegen — do not edit."
        assert lines[1] == f"// Plan: project demo, branch main, plan {PLAN_HASH}."
        assert item.content.endswith("\n") and not item.content.endswith("\n\n")


# --- structure: what the owner asked for ------------------------------------------------
def test_there_is_no_function_per_event(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    for name, content in files.items():
        functions = re.findall(r"\b(?:func|fun|function) (\w+)", content)
        if "TriplTransport" in name or "triplTransport" in name:
            continue
        assert len(functions) == 1, f"{name} declares {functions}"


def test_structured_keeps_the_wrapper_signature_with_narrowed_types(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    swift = files["swift/AppEvents.swift"]
    assert (
        "public static func log(category: Category, action: Action, label: String? = nil, "
        "properties: [String: Any] = [:])" in swift
    )
    assert (
        "Analytics.shared.log(category: category.rawValue, action: action.rawValue, "
        "label: label, properties: properties)" in swift
    )
    # A variable-backed value contributes the variable's allowed values.
    assert 'case confirm = "confirm"' in swift and 'case start = "start"' in swift
    # A free `${promo_id}` keeps `label` a String rather than inventing an enum.
    assert "enum Label" not in swift
    kotlin = files["kotlin/AppEvents.kt"]
    assert "Analytics.log(category = category.value, action = action.value" in kotlin
    assert "properties: Map<String, Any?> = emptyMap()" in kotlin
    ts = files["ts/appEvents.ts"]
    assert "properties: Readonly<Record<string, unknown>> = {}" in ts
    assert "import { analytics } from './analytics';" in ts
    assert "analytics.log(category, action, label, properties);" in ts
    assert "export type Category = (typeof Category)[keyof typeof Category];" in ts


def test_known_events_list_only_fully_literal_events(tmp_path: Path) -> None:
    swift = _by_name(_generate(tmp_path))["swift/AppEvents.swift"]
    known = re.findall(r'KnownEvent\(identity: "([^"]+)"', swift)
    # The two events with ${…} holes cannot be spelled as constants and are left out.
    assert known == ["1st run:open:card", "default:open:card", "home:open:card"]


def test_screen_view_types_screens_and_uses_the_shared_destination(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    swift = files["swift/ScreenTracking.swift"]
    assert "public enum ScreenType: String" in swift and "public enum ScreenId: String" in swift
    assert 'case checkoutStart = "Checkout Start"' in swift
    assert 'TriplTracking.send(eventType: "screen", name: type.rawValue' in swift
    ts = files["ts/screenTracking.ts"]
    assert "import { triplSend } from './triplTransport';" in ts
    assert "triplSend('screen', type, { 'type': type, 'id': id }, properties);" in ts


def test_named_is_one_typed_value_per_event_and_one_track(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    swift = files["swift/LegacyTracking.swift"]
    assert "case homeScreenView(HomeScreenView)" in swift
    assert "case checkoutStart\n" in swift  # fixes every field: no payload
    assert "public static func track(_ event: LegacyEvent)" in swift
    assert "Analytics.shared.logEvent(event.name, parameters: event.properties)" in swift
    # A token in the name is a typed parameter, filled into the name and fixed values.
    assert "public let sheetId: SheetId" in swift
    assert 'public var name: String { "promo_sheet_\\(sheetId.rawValue)_shown" }' in swift
    assert 'properties["mode"] = "promo_\\(sheetId.rawValue)"' in swift
    kotlin = files["kotlin/LegacyTracking.kt"]
    assert "sealed interface LegacyEvent {" in kotlin
    assert "object CheckoutStart : LegacyEvent {" in kotlin
    assert 'get() = "promo_sheet_${sheetId.value}_shown"' in kotlin
    ts = files["ts/legacyTracking.ts"]
    assert (
        "export function track<K extends LegacyEventName>(name: K, props: LegacyEventProps[K])"
        in ts
    )
    assert "readonly 'Home Screen View': {" in ts
    assert "readonly 'checkout:start': Record<string, never>;" in ts


def test_self_describing_is_one_class_per_schema(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    swift = files["swift/SdTracking.swift"]
    assert "public struct CheckoutStartedV1_0_0: SdEvent" in swift
    assert "public struct CheckoutStartedV2_0_0: SdEvent" in swift
    assert "public struct PromoSheetViewed: SdEvent" in swift  # one version: no suffix
    kotlin = files["kotlin/SdTracking.kt"]
    # No open values: Kotlin has no data class without constructor parameters.
    assert "object PromoSheetViewed : SdEvent {" in kotlin
    assert "name = event.schema, fields = emptyMap(), properties = event.data" in kotlin
    ts = files["ts/sdTracking.ts"]
    assert (
        "export type PromoSheetViewed = "
        "SdEventProps['iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0'];" in ts
    )


def test_deprecated_events_are_marked_and_archived_ones_are_absent(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    assert (
        '@available(*, deprecated, message: "Deprecated in the tracking plan.")'
        in files["swift/LegacyTracking.swift"]
    )
    assert '@Deprecated("Deprecated in the tracking plan.")' in files["kotlin/LegacyTracking.kt"]
    assert "@deprecated Deprecated in the tracking plan." in files["ts/legacyTracking.ts"]
    assert all("old_event" not in content for content in files.values())


def test_the_typescript_is_strict_mode_shaped(tmp_path: Path) -> None:
    """What ``tsc --strict --noUnusedLocals`` would object to, checked without tsc."""
    for name, content in _by_name(_generate(tmp_path)).items():
        if not name.startswith("ts/"):
            continue
        assert ": any" not in content and "<any>" not in content, name
        assert "// @ts-" not in content, name
        imported = re.findall(r"import \{ ([^}]+) \} from", content)
        for group in imported:
            for symbol in (part.strip() for part in group.split(",")):
                uses = len(re.findall(rf"\b{re.escape(symbol)}\b", content))
                assert uses > 1, f"{name} imports {symbol} and never uses it"
        if "const resolvedName" in content:
            assert content.count("resolvedName") > 1, name


def test_kotlin_package_and_file_names(tmp_path: Path) -> None:
    files = _generate(tmp_path)
    assert {item.path.name for item in files if item.language == "ts"} == {
        "appEvents.ts",
        "legacyTracking.ts",
        "screenTracking.ts",
        "sdTracking.ts",
        "triplTransport.ts",
    }
    for item in files:
        if item.language == "kotlin":
            assert "\npackage com.example.tracking\n" in item.content


def test_a_variable_is_found_by_any_of_its_token_spellings() -> None:
    model = _model()
    assert model.allowed("sheet_id") == ("spring", "summer")
    assert model.allowed("sheet") == ("spring", "summer")  # a binding's spelling
    assert model.allowed("promo_id") is None  # no allowed values: free text
    assert model.revision == REVISION and model.branch == "main"


def test_fixed_values_are_typed_by_their_field_type(tmp_path: Path) -> None:
    files = _by_name(_generate(tmp_path))
    # A boolean field fixed to "true" and a number field fixed to "4.5".
    swift_legacy = files["swift/LegacyTracking.swift"]
    assert '["is_first": true, "mode": "checkout", "platform": "ios"]' in swift_legacy
    assert 'properties["price"] = 4.5' in files["swift/SdTracking.swift"]
    assert 'mapOf("price" to 4.5, "sku" to "none")' in files["kotlin/SdTracking.kt"]
    ts = files["ts/legacyTracking.ts"]
    assert "'checkout:start': { 'is_first': true, 'mode': 'checkout', 'platform': 'ios' }" in ts
    assert "Readonly<Record<string, unknown>> } = {" in ts
    assert "typeof fixed === 'string' ? triplInterpolate(fixed, values) : fixed" in ts
    # A value that is not one of its type stays the plan's string.
    raw = json.loads((FIXTURES / "model.json").read_text(encoding="utf-8"))
    legacy = next(item for item in raw["event_types"] if item["name"] == "legacy")
    legacy["events"][3]["field_values"]["is_first"] = "maybe"
    config = load(FIXTURES / "check.yml")
    swift = {
        item.path.name: item.content
        for item in generate(config, parse_model(raw), "demo", out=tmp_path, languages=["swift"])
    }["LegacyTracking.swift"]
    assert '"is_first": "maybe"' in swift


def test_an_events_own_override_types_its_token() -> None:
    raw = json.loads((FIXTURES / "model.json").read_text(encoding="utf-8"))
    legacy = next(item for item in raw["event_types"] if item["name"] == "legacy")
    promo = next(event for event in legacy["events"] if "${sheet_id}" in event["identity"])
    promo["overrides"] = {"sheet_id": ["autumn"]}
    model = parse_model(raw)
    legacy_model = model.event_type("legacy")
    assert legacy_model is not None
    event = next(item for item in legacy_model.events if "${" in item.identity)
    assert model.allowed_for(event, "sheet_id") == ("autumn",)
    assert model.allowed("sheet_id") == ("spring", "summer")
    # Absent overrides (an older server) fall back to the variable.
    plain_model = _model()
    plain_legacy = plain_model.event_type("legacy")
    assert plain_legacy is not None
    plain = next(item for item in plain_legacy.events if "${" in item.identity)
    assert plain.overrides == {}
    assert plain_model.allowed_for(plain, "sheet_id") == ("spring", "summer")
    # The list form of overrides reads the same as the mapping form.
    promo["overrides"] = [{"token": "sheet_id", "allowed_values": ["autumn"]}]
    listed = parse_model(raw).event_type("legacy")
    assert listed is not None
    listed_event = next(item for item in listed.events if "${" in item.identity)
    assert model.allowed_for(listed_event, "sheet_id") == ("autumn",)
    config = load(FIXTURES / "check.yml")
    files = {
        item.path.name: item.content
        for item in generate(config, model, "demo", out=Path("out"), languages=["swift"])
    }
    swift = files["LegacyTracking.swift"]
    assert 'case autumn = "autumn"' in swift and 'case spring = "spring"' not in swift


def test_token_and_rule_key_grammar_match_the_backend() -> None:
    from tripl_cli.codegen.model import rule_keys, tokens

    # A token is anything but `}` between `${` and `}`, empty included.
    assert tokens("a_${sheet id}_${x.y-z}_${}") == ["sheet id", "x.y-z", ""]
    # A rule key is `{…}` with at least one character, never a `${…}`'s braces.
    assert rule_keys("{category}:${step}:{label}:{}") == ["category", "label"]
    assert rule_keys("{a b}") == ["a b"]


def test_token_names_become_identifiers() -> None:
    raw = json.loads((FIXTURES / "model.json").read_text(encoding="utf-8"))
    legacy = next(item for item in raw["event_types"] if item["name"] == "legacy")
    legacy["events"].append(
        {"identity": "tab_${tab name}", "name": "tab_${tab name}", "status": "active"}
    )
    config = load(FIXTURES / "check.yml")
    for item in generate(config, parse_model(raw), "demo", out=Path("out")):
        if item.event_type != "legacy":
            continue
        ident = {"swift": "tabName", "kotlin": "tabName", "ts": "'tab name'"}[item.language]
        assert ident in item.content


def test_literal_parts_merge_before_escaping_so_no_live_interpolation_forms() -> None:
    from tripl_cli.codegen.context import interpolation
    from tripl_cli.codegen.languages import DIALECTS

    ts = DIALECTS["ts"]
    # `$` then an unresolved `{app}`: escaped apart they would spell a live `${app}`.
    text = interpolation(ts, "cost {x} $" + "{app}", {"x": "x"}, braces=True)
    assert text == "`cost ${x} \\${app}`"
    merged = ts.interpolate([(False, "$"), (False, "{app}"), (True, "v")])
    assert merged == "`\\${app}${v}`"


def test_type_names_overrides_are_checked_per_target_language(tmp_path: Path) -> None:
    # `object` is fine in Swift and TypeScript, a keyword in Kotlin.
    config = "codegen: {out: out}\nevent_types: {se: {codegen: {type_names: {category: object}}}}"
    with pytest.raises(TriplConfigError, match="'object' is not an identifier in kotlin"):
        _generate(tmp_path, config)
    # A language's own type would be shadowed by the nested declaration.
    config = "codegen: {out: out}\nevent_types: {se: {codegen: {type_names: {category: Record}}}}"
    with pytest.raises(TriplConfigError, match="would shadow ts's own Record"):
        _generate(tmp_path, config)
    # Only the languages the event type generates are asked.
    config = (
        "codegen: {out: out}\n"
        "event_types: {se: {codegen: {languages: [swift], type_names: {category: Record}}}}"
    )
    assert _generate(tmp_path, config)


def test_the_header_hashes_the_generated_files_when_the_export_has_no_plan_hash(
    tmp_path: Path,
) -> None:
    raw = json.loads((FIXTURES / "model.json").read_text(encoding="utf-8"))
    del raw["plan_hash"]
    config = load(FIXTURES / "check.yml")
    first = generate(config, parse_model(raw), "demo", out=tmp_path)
    headers = {item.content.splitlines()[1] for item in first}
    assert len(headers) == 1
    (header,) = headers
    assert re.fullmatch(r"// Plan: project demo, branch main, plan [0-9a-f]{64}\.", header)
    assert "\x00" not in "".join(item.content for item in first)
    # Deterministic, and independent of the revision id.
    raw["revision"] = "00000000-0000-4000-8000-000000000001"
    again = generate(config, parse_model(raw), "demo", out=tmp_path)
    assert [item.content for item in again] == [item.content for item in first]


# --- escaping: a plan value is data, never code ----------------------------------------
@pytest.mark.parametrize(
    ("raw", "swift", "kotlin", "ts"),
    [
        ('say "hi"', r'"say \"hi\""', r'"say \"hi\""', "'say \"hi\"'"),
        ("it's", '"it\'s"', '"it\'s"', r"'it\'s'"),
        ("a\\(b)", r'"a\\(b)"', r'"a\\(b)"', r"'a\\(b)'"),
        ("${x}", '"${x}"', r'"\${x}"', "'${x}'"),
        ("line\nbreak", r'"line\nbreak"', r'"line\nbreak"', r"'line\nbreak'"),
        # U+2028 ends a line in a pre-ES2019 JS string literal, and is invisible in every
        # editor: each language spells it as an escape.
        ("\u2028", r'"\u{2028}"', r'"\u2028"', r"'\u2028'"),
    ],
)
def test_string_literals_escape_per_language(raw: str, swift: str, kotlin: str, ts: str) -> None:
    assert swift_string(raw) == swift
    assert kotlin_string(raw) == kotlin
    assert ts_string(raw) == ts


def test_hostile_plan_values_stay_inert(tmp_path: Path) -> None:
    raw = json.loads((FIXTURES / "model.json").read_text(encoding="utf-8"))
    # No `${`: that would make it a plan token, and the field free text (no enum at all).
    hostile = "x\"); drop(); /* */ $boom \\(pwn) `tick` 'q'\nnext"
    raw["event_types"][0]["events"][0]["field_values"]["category"] = hostile
    config = load(FIXTURES / "check.yml")
    literal = {"swift": swift_string, "kotlin": kotlin_string, "ts": ts_string}
    for item in generate(config, parse_model(raw), "demo", out=tmp_path):
        if item.event_type != "se":
            continue
        # The value appears as ONE string literal of the target language...
        assert literal[item.language](hostile) in item.content
        # ...and its line break never reaches the source: `next` never starts a line.
        assert not any(line.lstrip().startswith("next") for line in item.content.splitlines())


# --- customisation ---------------------------------------------------------------------
def test_a_custom_template_overrides_the_builtin_for_its_language(tmp_path: Path) -> None:
    template = tmp_path / "structured.swift.mustache"
    template.write_text(
        "{{header}}\n"
        "// {{namespace}}.{{function.name}}({{function.signature}})\n"
        "{{#enums}}\n"
        "// {{name}}:{{#cases}} {{ident}}={{literal}}{{/cases}}\n"
        "{{/enums}}\n",
        encoding="utf-8",
    )
    config = f"""
codegen: {{out: out}}
event_types:
  se:
    codegen:
      style: structured
      languages: [swift, ts]
      template: {{swift: "{template}"}}
"""
    files = _by_name(_generate(tmp_path, config))
    swift = files["swift/SeTracking.swift"]
    assert '// Category: _1stRun="1st run" checkout="checkout" default_="default"' in swift
    assert "// SeTracking.track(category: Category, action: Action," in swift
    # The other language keeps the built-in template.
    assert "export function track(" in files["ts/seTracking.ts"]


def test_a_broken_custom_template_is_a_config_error(tmp_path: Path) -> None:
    template = tmp_path / "broken.mustache"
    template.write_text("{{#enums}}\n{{nope}}\n{{/enums}}\n", encoding="utf-8")
    config = f"""
event_types:
  se: {{codegen: {{languages: [ts], template: "{template}"}}}}
"""
    with pytest.raises(TriplConfigError, match=r"broken\.mustache:2: unknown value \{\{nope\}\}"):
        _generate(tmp_path, config)


def test_type_names_and_style_inference(tmp_path: Path) -> None:
    config = """
event_types:
  se:
    codegen: {languages: [kotlin], type_names: {namespace: AppEvents, category: EventCategory}}
  legacy:
    codegen: {languages: [kotlin]}
"""
    files = _by_name(_generate(tmp_path, config))
    # A name rule means structured; no name rule means named.
    assert "enum class EventCategory(val value: String)" in files["kotlin/AppEvents.kt"]
    assert "sealed interface LegacyEvent" in files["kotlin/LegacyTracking.kt"]


def test_lang_filter_and_per_type_languages(tmp_path: Path) -> None:
    files = _generate(tmp_path, languages=["ts"])
    assert {item.language for item in files} == {"ts"}


# --- refusals --------------------------------------------------------------------------
def test_no_codegen_block_is_a_config_error(tmp_path: Path) -> None:
    config = "event_types: {se: {calls: [{function: log}]}}"
    with pytest.raises(TriplConfigError, match="no event type has a `codegen:` block"):
        _generate(tmp_path, config)


def test_an_event_type_missing_from_the_plan_fails(tmp_path: Path) -> None:
    config = "event_types: {nope: {codegen: {style: named}}}"
    with pytest.raises(TriplError, match="the plan has no event type named 'nope'"):
        _generate(tmp_path, config)


@pytest.mark.parametrize(
    ("config", "message"),
    [
        ("event_types: {se: {codegen: {style: fancy}}}", "is not one of structured"),
        ("event_types: {se: {codegen: {languages: [java]}}}", "is not a codegen language"),
        ("event_types: {se: {codegen: {bogus: 1}}}", "unknown key"),
        ("event_types: {se: {codegen: {type_names: {namespace: 'App Events'}}}}", "identifier"),
        (
            "event_types: {se: {codegen: {template: a.mustache}}}",
            "a single template needs exactly one entry",
        ),
        ("event_types: {se: {codegen: {transport: {ts: {args: {}}}}}}", "needs `function:`"),
        ("codegen: {kotlin_package: 'com..x'}\nevent_types: {}", "is not a package name"),
    ],
)
def test_bad_codegen_blocks_are_refused(tmp_path: Path, config: str, message: str) -> None:
    from tripl_cli.check import yamlish

    with pytest.raises(TriplConfigError, match=re.escape(message)):
        parse(yamlish.loads(config), path=None, base=tmp_path)


def test_a_bare_transport_reuses_the_matching_call_mapping(tmp_path: Path) -> None:
    from tripl_cli.check import yamlish

    config = parse(
        yamlish.loads(
            """
event_types:
  legacy:
    calls: [{function: "Analytics.shared.logEvent", name_arg: 0, properties_arg: parameters}]
    codegen: {transport: {swift: "Analytics.shared.logEvent", kotlin: "Other.send"}}
"""
        ),
        path=None,
        base=tmp_path,
    )
    codegen = config.event_types[0].codegen
    assert codegen is not None
    swift = codegen.transport["swift"]
    assert swift.positional == ("name",)
    assert swift.labelled == (("parameters", "properties"),)
    assert not codegen.transport["kotlin"].mapped  # no matching call: the style default


def test_without_an_output_directory_generation_asks_for_one(tmp_path: Path) -> None:
    from tripl_cli.check import yamlish

    config = parse(yamlish.loads("event_types:\n  se:\n    codegen:\n"), path=None, base=tmp_path)
    with pytest.raises(TriplConfigError, match="say where the swift files go"):
        generate(config, _model(), "demo")


# --- the opt-in compiler check ----------------------------------------------------------
@pytest.mark.skipif(shutil.which("tsc") is None, reason="no TypeScript compiler on PATH")
def test_generated_typescript_compiles(tmp_path: Path) -> None:  # pragma: no cover - opt-in
    """Compiles the TS output, and proves a wrong enum value is a compile error.

    Skipped where ``tsc`` is not installed, which is the CLI's own test
    environment (it depends on httpx alone); run it where Node is available.
    """
    ts_dir = tmp_path / "ts"
    for item in _generate(ts_dir, languages=["ts"]):  # one language: written into ts_dir itself
        item.path.parent.mkdir(parents=True, exist_ok=True)
        item.path.write_text(item.content, encoding="utf-8")
    (ts_dir / "analytics.ts").write_text(
        "export const analytics = { log(..._args: unknown[]): void {} };\n", encoding="utf-8"
    )
    (ts_dir / "ok.ts").write_text(
        "import { log } from './appEvents';\n"
        "import { track } from './legacyTracking';\n"
        "log('home', 'open', 'card');\n"
        "track('promo_sheet_${sheet_id}_shown', { sheet_id: 'spring' });\n"
        "track('checkout:start', {});\n",
        encoding="utf-8",
    )
    flags = ["--strict", "--noEmit", "--noUnusedLocals", "--target", "es2020", "--module", "es2020"]
    ok = subprocess.run(
        ["tsc", *flags, *(str(path) for path in sorted(ts_dir.glob("*.ts")))],
        capture_output=True,
        text=True,
        check=False,
    )
    assert ok.returncode == 0, ok.stdout + ok.stderr
    (ts_dir / "bad.ts").write_text(
        "import { log } from './appEvents';\nlog('map', 'open', 'card');\n", encoding="utf-8"
    )
    bad = subprocess.run(
        ["tsc", *flags, str(ts_dir / "bad.ts")], capture_output=True, text=True, check=False
    )
    assert bad.returncode != 0
    assert "'\"map\"' is not assignable" in bad.stdout or "map" in bad.stdout
