// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: se (structured). Regenerate with `tripl codegen`.

package com.example.tracking

/**
 * Typed values for the `se` event type (structured): one enum per
 * plan field, and the wrapper's own call with its arguments narrowed to them.
 */
object AppEvents {
    enum class Category(val value: String) {
        _1ST_RUN("1st run"),
        CHECKOUT("checkout"),
        DEFAULT("default"),
        HOME("home");
    }

    enum class Action(val value: String) {
        CONFIRM("confirm"),
        OPEN("open"),
        START("start"),
        TAP("tap");
    }

    data class KnownEvent(
        val identity: String,
        val category: Category,
        val action: Action,
        val label: String,
    )

    /** Every planned combination, checked by the compiler against the enums above. */
    val knownEvents: List<KnownEvent> = listOf(
        KnownEvent(identity = "1st run:open:card", category = Category._1ST_RUN, action = Action.OPEN, label = "card"),
        KnownEvent(identity = "default:open:card", category = Category.DEFAULT, action = Action.OPEN, label = "card"),
        KnownEvent(identity = "home:open:card", category = Category.HOME, action = Action.OPEN, label = "card"),
    )

    fun log(category: Category, action: Action, label: String? = null, properties: Map<String, Any?> = emptyMap()) {
        Analytics.log(category = category.value, action = action.value, label = label, properties = properties)
    }
}
