// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: legacy (named). Regenerate with `tripl codegen`.

package com.example.tracking

/**
 * The `legacy` events (named): one type per planned event, carrying
 * exactly the values the plan leaves open. Send one with `LegacyTracking.track`.
 */
sealed interface LegacyEvent {
    /** The event's name, exactly as the plan spells it. */
    val name: String
    val properties: Map<String, Any?>

    enum class Platform(val value: String) {
        ANDROID("android"),
        IOS("ios");
    }

    enum class SheetId(val value: String) {
        SPRING("spring"),
        SUMMER("summer");
    }

    /** `Home Screen View` */
    data class HomeScreenView(
        val mode: String,
        val isFirst: Boolean? = null,
        val platform: Platform? = null,
    ) : LegacyEvent {
        override val name: String get() = "Home Screen View"
        override val properties: Map<String, Any?> get() = buildMap<String, Any?> {
            put("mode", mode)
            isFirst?.let { put("is_first", it) }
            platform?.let { put("platform", it.value) }
        }
    }

    /** `checkout:start` */
    @Deprecated("Deprecated in the tracking plan.")
    object CheckoutStart : LegacyEvent {
        override val name: String get() = "checkout:start"
        override val properties: Map<String, Any?> get() = mapOf("is_first" to true, "mode" to "checkout", "platform" to "ios")
    }

    /** `promo_sheet_${sheet_id}_shown` */
    data class PromoSheetSheetIdShown(
        val sheetId: SheetId,
        val isFirst: Boolean? = null,
        val platform: Platform? = null,
    ) : LegacyEvent {
        override val name: String get() = "promo_sheet_${sheetId.value}_shown"
        override val properties: Map<String, Any?> get() = buildMap<String, Any?> {
            put("mode", "promo_${sheetId.value}")
            isFirst?.let { put("is_first", it) }
            platform?.let { put("platform", it.value) }
        }
    }

    /** `trial_started` */
    data class TrialStarted(
        val isFirst: Boolean? = null,
        val platform: Platform? = null,
    ) : LegacyEvent {
        override val name: String get() = "trial_started"
        override val properties: Map<String, Any?> get() = buildMap<String, Any?> {
            put("mode", "trial")
            isFirst?.let { put("is_first", it) }
            platform?.let { put("platform", it.value) }
        }
    }
}

object LegacyTracking {
    fun track(event: LegacyEvent) {
        TriplTracking.send(eventType = "legacy", name = event.name, fields = emptyMap(), properties = event.properties)
    }
}
