// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: screen (screen_view). Regenerate with `tripl codegen`.

package com.example.tracking

/**
 * Typed screen views for the `screen` event type (screen_view): the plan's
 * screen types (and ids, where it has them), and the wrapper's call narrowed to them.
 */
object ScreenTracking {
    enum class ScreenType(val value: String) {
        CHECKOUT_START("Checkout Start"),
        HOME_VIEW("HomeView");
    }

    enum class ScreenId(val value: String) {
        CHECKOUT_START("checkout:start"),
        HOME("home");
    }

    data class KnownEvent(
        val identity: String,
        val type: ScreenType,
    )

    /** Every planned screen view, checked by the compiler against the enums above. */
    val knownEvents: List<KnownEvent> = listOf(
        KnownEvent(identity = "Checkout Start", type = ScreenType.CHECKOUT_START),
        KnownEvent(identity = "HomeView", type = ScreenType.HOME_VIEW),
    )

    fun track(type: ScreenType, id: ScreenId? = null, properties: Map<String, Any?> = emptyMap()) {
        TriplTracking.send(eventType = "screen", name = type.value, fields = mapOf("type" to type.value, "id" to id?.value), properties = properties)
    }
}
