// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: sd (self_describing). Regenerate with `tripl codegen`.

package com.example.tracking

/**
 * A `sd` event (self_describing): one class per schema, carrying exactly the
 * values the plan leaves open. Send one with `SdTracking.track`.
 */
sealed interface SdEvent {
    /** The event's identity, exactly as the plan spells it. */
    val name: String
    /** The schema URI the event is sent with. */
    val schema: String
    val data: Map<String, Any?>

    /** `iglu:com.example/checkout_started/jsonschema/1-0-0` */
    @Deprecated("Deprecated in the tracking plan.")
    data class CheckoutStartedV1_0_0(
        val sku: String,
        val price: Double? = null,
    ) : SdEvent {
        override val name: String get() = "iglu:com.example/checkout_started/jsonschema/1-0-0"
        override val schema: String get() = "iglu:com.example/checkout_started/jsonschema/1-0-0"
        override val data: Map<String, Any?> get() = buildMap<String, Any?> {
            put("sku", sku)
            price?.let { put("price", it) }
        }
    }

    /** `iglu:com.example/checkout_started/jsonschema/2-0-0` */
    data class CheckoutStartedV2_0_0(
        val sku: String,
        val price: Double? = null,
    ) : SdEvent {
        override val name: String get() = "iglu:com.example/checkout_started/jsonschema/2-0-0"
        override val schema: String get() = "iglu:com.example/checkout_started/jsonschema/2-0-0"
        override val data: Map<String, Any?> get() = buildMap<String, Any?> {
            put("sku", sku)
            price?.let { put("price", it) }
        }
    }

    /** `iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0` */
    object PromoSheetViewed : SdEvent {
        override val name: String get() = "iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0"
        override val schema: String get() = "iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0"
        override val data: Map<String, Any?> get() = mapOf("price" to 4.5, "sku" to "none")
    }
}

object SdTracking {
    fun track(event: SdEvent) {
        TriplTracking.send(eventType = "sd", name = event.schema, fields = emptyMap(), properties = event.data)
    }
}
