// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Regenerate with `tripl codegen`.

package com.example.tracking

/**
 * Where generated trackers send an event whose type has no `transport` configured in
 * `.tripl/check.yml`. Implement it once, over the app's own analytics wrapper, and set
 * [TriplTracking.destination] at startup.
 *
 * `name` is the event's identity (a self-describing event's schema URI), or null when the
 * event type has no name rule to build one from; `fields` are the plan's field values.
 */
fun interface TriplDestination {
    fun track(eventType: String, name: String?, fields: Map<String, String>, properties: Map<String, Any?>)
}

object TriplTracking {
    /** Until it is set, calls through the generated trackers are dropped. */
    @Volatile
    var destination: TriplDestination? = null

    fun send(eventType: String, name: String?, fields: Map<String, String?>, properties: Map<String, Any?>) {
        val present = buildMap<String, String> {
            fields.forEach { (key, value) -> if (value != null) put(key, value) }
        }
        destination?.track(eventType, name, present, properties)
    }
}
