// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: app (named). Regenerate with `tripl codegen`.

/// The `app` event names, exactly as the plan spells them.
public enum AcmeAppEventNames {
    public static let checkoutStarted = "checkout_started"
    @available(*, deprecated, message: "Deprecated in the tracking plan.")
    public static let class_ = "class"
    public static let paywallShown = "paywall_shown"
    public static func promoPromoCodeApplied(promoCode: String) -> String { "promo_\(promoCode)_applied" }
}

/// The `app` property keys.
public enum AcmeAppEventKeys {
    public static let isTrial = "is_trial"
    public static let planTier = "plan_tier"
    public static let source = "source"
}
