// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: screen (screen_view). Regenerate with `tripl codegen`.

/// The planned `screen` screens: a (type, id) pair the plan does not list does not compile.
public enum AcmeScreen: CaseIterable, Sendable {
    case checkoutCart
    case checkoutConfirm
    case home
    case paywallAnnual
    case paywallMonthly
    case settings

    public var type: String {
        switch self {
        case .checkoutCart: return "checkout"
        case .checkoutConfirm: return "checkout"
        case .home: return "home"
        case .paywallAnnual: return "paywall"
        case .paywallMonthly: return "paywall"
        case .settings: return "settings"
        }
    }

    public var id: String? {
        switch self {
        case .checkoutCart: return "cart"
        case .checkoutConfirm: return "confirm"
        case .home: return "main"
        case .paywallAnnual: return "annual"
        case .paywallMonthly: return "monthly"
        case .settings: return nil
        }
    }
}

public enum AcmeScreens {
    public static func screen(_ screen: AcmeScreen) {
        AcmeTracker.shared.trackScreen(type: screen.type, id: screen.id)
    }
}
