// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

/// The plan's values for `category` (se).
public enum AcmeCategory {
    public static let checkout = "checkout"
    public static let home = "home"
    public static let paywall = "paywall"
}

/// The plan's values for `action` (se).
public enum AcmeAction {
    public static let close = "close"
    public static let open = "open"
    public static let show = "show"
    public static let tap = "tap"
    public static let view = "view"
}

/// The plan's values for `label` (se).
public enum AcmeLabel {
    public static let _1stCard = "1st_card"
    public static let default_ = "default"
    public static let offer = "offer"
    public static let payButton = "pay_button"
    public static let paywall = "paywall"
    public static let promoSheet = "promo-sheet"
    public static let promoSheet2 = "promo_sheet"
}

/// The plan's values for `property` (se).
public enum AcmeProperty {
    public static let class_ = "class"
}

/// Builds a `se` event as the team's own AcmeEvent, to be handed on.
public enum AcmeStructured {
    public static func event(
        category: String,
        action: String,
        label: String? = nil,
        property: String? = nil,
        value: Double? = nil
    ) -> AcmeEvent {
        AcmeEvent(
            category: category,
            action: action,
            label: label,
            property: property,
            value: value
        )
    }
}
