// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Regenerate with `tripl codegen`.

/// Where generated trackers send an event whose type has no `transport` configured in
/// `.tripl/check.yml`. Implement it once, over the app's own analytics wrapper, and set
/// `TriplTracking.destination` at startup.
public protocol TriplDestination: AnyObject {
    /// - Parameters:
    ///   - eventType: the plan's event type name.
    ///   - name: the event's identity (a self-describing event's schema URI); `nil` when the
    ///     event type has no name rule to build one from.
    ///   - fields: the plan's field values, as strings.
    ///   - properties: everything else the call carried.
    func track(eventType: String, name: String?, fields: [String: String], properties: [String: Any])
}

public enum TriplTracking {
    /// Until it is set, calls through the generated trackers are dropped.
    nonisolated(unsafe) public static var destination: (any TriplDestination)?

    public static func send(
        eventType: String,
        name: String?,
        fields: [String: String?],
        properties: [String: Any]
    ) {
        destination?.track(
            eventType: eventType,
            name: name,
            fields: fields.compactMapValues { $0 },
            properties: properties
        )
    }
}
