// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

/** The plan's values for `label` (se). */
export const AcmeLabel = {
  _1stCard: '1st_card',
  default_: 'default',
  offer: 'offer',
  payButton: 'pay_button',
  paywall: 'paywall',
  promoSheet: 'promo-sheet',
  promoSheet2: 'promo_sheet',
} as const;
export type AcmeLabel = (typeof AcmeLabel)[keyof typeof AcmeLabel];
