// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: screen (screen_view). Regenerate with `tripl codegen`.

import { acmeTracker } from './acmeTracker';

/** The planned `screen` screens: a (type, id) pair the plan does not list does not type-check. */
export const AcmeScreens = {
  checkoutCart: { type: 'checkout', id: 'cart' },
  checkoutConfirm: { type: 'checkout', id: 'confirm' },
  home: { type: 'home', id: 'main' },
  paywallAnnual: { type: 'paywall', id: 'annual' },
  paywallMonthly: { type: 'paywall', id: 'monthly' },
  settings: { type: 'settings', id: null },
} as const;
export type AcmeScreen = (typeof AcmeScreens)[keyof typeof AcmeScreens];

export function screen(screen: AcmeScreen): void {
  acmeTracker.trackScreen(screen.type, screen.id);
}
