// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

import { acmeEvent, type AcmeEvent } from './acmeEvent';
import type { AcmeCategory } from './acmeCategory';
import type { AcmeAction } from './acmeAction';
import type { AcmeLabel } from './acmeLabel';
import type { AcmeProperty } from './acmeProperty';

/** Builds a `se` event as the team's own AcmeEvent, to be handed on. */
export function event(
  category: AcmeCategory,
  action: AcmeAction,
  label?: AcmeLabel,
  property?: AcmeProperty,
  value?: number,
): AcmeEvent {
  return acmeEvent({ category: category, action: action, label: label, property: property, value: value });
}
