// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

/** The plan's values for `action` (se). */
export const AcmeAction = {
  close: 'close',
  open: 'open',
  show: 'show',
  tap: 'tap',
  view: 'view',
} as const;
export type AcmeAction = (typeof AcmeAction)[keyof typeof AcmeAction];
