// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

/** The plan's values for `category` (se). */
export const AcmeCategory = {
  checkout: 'checkout',
  home: 'home',
  paywall: 'paywall',
} as const;
export type AcmeCategory = (typeof AcmeCategory)[keyof typeof AcmeCategory];
