// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: app (named). Regenerate with `tripl codegen`.

/** The `app` event names, exactly as the plan spells them. */
export const AcmeAppEventNames = {
  checkoutStarted: 'checkout_started',
  /** @deprecated Deprecated in the tracking plan. */
  class_: 'class',
  paywallShown: 'paywall_shown',
  promoPromoCodeApplied: (promoCode: string): string => `promo_${promoCode}_applied`,
} as const;

/** The `app` property keys. */
export const AcmeAppEventKeys = {
  isTrial: 'is_trial',
  planTier: 'plan_tier',
  source: 'source',
} as const;
