// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

/** The plan's values for `property` (se). */
export const AcmeProperty = {
  class_: 'class',
} as const;
export type AcmeProperty = (typeof AcmeProperty)[keyof typeof AcmeProperty];
