// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: se (structured). Regenerate with `tripl codegen`.

import { analytics } from './analytics';

export const Category = {
  _1stRun: '1st run',
  checkout: 'checkout',
  default_: 'default',
  home: 'home',
} as const;
export type Category = (typeof Category)[keyof typeof Category];

export const Action = {
  confirm: 'confirm',
  open: 'open',
  start: 'start',
  tap: 'tap',
} as const;
export type Action = (typeof Action)[keyof typeof Action];

export interface KnownEvent {
  readonly identity: string;
  readonly category: Category;
  readonly action: Action;
  readonly label: string;
}

/** Every planned combination, checked by the compiler against the types above. */
export const knownEvents: readonly KnownEvent[] = [
  { identity: '1st run:open:card', category: Category._1stRun, action: Action.open, label: 'card' },
  { identity: 'default:open:card', category: Category.default_, action: Action.open, label: 'card' },
  { identity: 'home:open:card', category: Category.home, action: Action.open, label: 'card' },
];

/**
 * The `se` event type (structured): the wrapper's own call, with its
 * arguments narrowed to the plan's values.
 */
export function log(category: Category, action: Action, label?: string, properties: Readonly<Record<string, unknown>> = {}): void {
  analytics.log(category, action, label, properties);
}
