// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: legacy (named). Regenerate with `tripl codegen`.

import { triplInterpolate, triplSend } from './triplTransport';

export const Platform = {
  android: 'android',
  ios: 'ios',
} as const;
export type Platform = (typeof Platform)[keyof typeof Platform];

export const SheetId = {
  spring: 'spring',
  summer: 'summer',
} as const;
export type SheetId = (typeof SheetId)[keyof typeof SheetId];

/**
 * The `legacy` events (named), keyed by their exact plan names: what each
 * takes is exactly the values the plan leaves open.
 */
export interface LegacyEventProps {
  /**
   * `Home Screen View`
   */
  readonly 'Home Screen View': {
    readonly 'mode': string;
    readonly 'is_first'?: boolean;
    readonly 'platform'?: Platform;
  };
  /**
   * `checkout:start`
   * @deprecated Deprecated in the tracking plan.
   */
  readonly 'checkout:start': Record<string, never>;
  /**
   * `promo_sheet_${sheet_id}_shown`
   */
  readonly 'promo_sheet_${sheet_id}_shown': {
    readonly 'sheet_id': SheetId;
    readonly 'is_first'?: boolean;
    readonly 'platform'?: Platform;
  };
  /**
   * `trial_started`
   */
  readonly 'trial_started': {
    readonly 'is_first'?: boolean;
    readonly 'platform'?: Platform;
  };
}

export type LegacyEventName = keyof LegacyEventProps;

const FIXED: { readonly [K in LegacyEventName]: Readonly<Record<string, unknown>> } = {
  'Home Screen View': {},
  'checkout:start': { 'is_first': true, 'mode': 'checkout', 'platform': 'ios' },
  'promo_sheet_${sheet_id}_shown': { 'mode': 'promo_${sheet_id}' },
  'trial_started': { 'mode': 'trial' },
};

const TOKENS: { readonly [K in LegacyEventName]: readonly string[] } = {
  'Home Screen View': [],
  'checkout:start': [],
  'promo_sheet_${sheet_id}_shown': ['sheet_id'],
  'trial_started': [],
};

export function track<K extends LegacyEventName>(name: K, props: LegacyEventProps[K]): void {
  const values = props as unknown as Readonly<Record<string, unknown>>;
  const resolvedName = triplInterpolate(name, values);
  const properties: Record<string, unknown> = {};
  for (const [key, fixed] of Object.entries(FIXED[name])) {
    properties[key] = typeof fixed === 'string' ? triplInterpolate(fixed, values) : fixed;
  }
  for (const [key, value] of Object.entries(values)) {
    if (value !== undefined && !TOKENS[name].includes(key)) {
      properties[key] = value;
    }
  }
  triplSend('legacy', resolvedName, {}, properties);
}
