// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: screen (screen_view). Regenerate with `tripl codegen`.

import { triplSend } from './triplTransport';

export const ScreenType = {
  checkoutStart: 'Checkout Start',
  homeView: 'HomeView',
} as const;
export type ScreenType = (typeof ScreenType)[keyof typeof ScreenType];

export const ScreenId = {
  checkoutStart: 'checkout:start',
  home: 'home',
} as const;
export type ScreenId = (typeof ScreenId)[keyof typeof ScreenId];

export interface KnownEvent {
  readonly identity: string;
  readonly type: ScreenType;
}

/** Every planned screen view, checked by the compiler against the types above. */
export const knownEvents: readonly KnownEvent[] = [
  { identity: 'Checkout Start', type: ScreenType.checkoutStart },
  { identity: 'HomeView', type: ScreenType.homeView },
];

/**
 * The `screen` screen views (screen_view): the wrapper's own call, with its
 * arguments narrowed to the plan's screen types and ids.
 */
export function track(type: ScreenType, id?: ScreenId, properties: Readonly<Record<string, unknown>> = {}): void {
  triplSend('screen', type, { 'type': type, 'id': id }, properties);
}
