// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: sd (self_describing). Regenerate with `tripl codegen`.

import { triplInterpolate, triplSend } from './triplTransport';

/**
 * The `sd` events (self_describing), keyed by their exact plan names: each
 * schema's data is exactly the values the plan leaves open.
 */
export interface SdEventProps {
  /**
   * `iglu:com.example/checkout_started/jsonschema/1-0-0`
   * @deprecated Deprecated in the tracking plan.
   */
  readonly 'iglu:com.example/checkout_started/jsonschema/1-0-0': {
    readonly 'sku': string;
    readonly 'price'?: number;
  };
  /**
   * `iglu:com.example/checkout_started/jsonschema/2-0-0`
   */
  readonly 'iglu:com.example/checkout_started/jsonschema/2-0-0': {
    readonly 'sku': string;
    readonly 'price'?: number;
  };
  /**
   * `iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0`
   */
  readonly 'iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0': Record<string, never>;
}

export type SdEventName = keyof SdEventProps;
export type CheckoutStartedV1_0_0 = SdEventProps['iglu:com.example/checkout_started/jsonschema/1-0-0'];
export type CheckoutStartedV2_0_0 = SdEventProps['iglu:com.example/checkout_started/jsonschema/2-0-0'];
export type PromoSheetViewed = SdEventProps['iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0'];

const SCHEMAS: { readonly [K in SdEventName]: string } = {
  'iglu:com.example/checkout_started/jsonschema/1-0-0': 'iglu:com.example/checkout_started/jsonschema/1-0-0',
  'iglu:com.example/checkout_started/jsonschema/2-0-0': 'iglu:com.example/checkout_started/jsonschema/2-0-0',
  'iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0': 'iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0',
};

const FIXED: { readonly [K in SdEventName]: Readonly<Record<string, unknown>> } = {
  'iglu:com.example/checkout_started/jsonschema/1-0-0': {},
  'iglu:com.example/checkout_started/jsonschema/2-0-0': {},
  'iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0': { 'price': 4.5, 'sku': 'none' },
};

const TOKENS: { readonly [K in SdEventName]: readonly string[] } = {
  'iglu:com.example/checkout_started/jsonschema/1-0-0': [],
  'iglu:com.example/checkout_started/jsonschema/2-0-0': [],
  'iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0': [],
};

export function track<K extends SdEventName>(name: K, props: SdEventProps[K]): void {
  const values = props as unknown as Readonly<Record<string, unknown>>;
  const schema = triplInterpolate(SCHEMAS[name], values);
  const data: Record<string, unknown> = {};
  for (const [key, fixed] of Object.entries(FIXED[name])) {
    data[key] = typeof fixed === 'string' ? triplInterpolate(fixed, values) : fixed;
  }
  for (const [key, value] of Object.entries(values)) {
    if (value !== undefined && !TOKENS[name].includes(key)) {
      data[key] = value;
    }
  }
  triplSend('sd', schema, {}, data);
}
