// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: se (structured). Regenerate with `tripl codegen`.

/// Typed values for the `se` event type (structured): one enum per
/// plan field, and the wrapper's own call with its arguments narrowed to them.
public enum AppEvents {
    public enum Category: String, CaseIterable, Sendable {
        case _1stRun = "1st run"
        case checkout = "checkout"
        case default_ = "default"
        case home = "home"
    }

    public enum Action: String, CaseIterable, Sendable {
        case confirm = "confirm"
        case open = "open"
        case start = "start"
        case tap = "tap"
    }

    public struct KnownEvent: Sendable {
        public let identity: String
        public let category: Category
        public let action: Action
        public let label: String
    }

    /// Every planned combination, checked by the compiler against the enums above.
    public static let knownEvents: [KnownEvent] = [
        KnownEvent(identity: "1st run:open:card", category: Category._1stRun, action: Action.open, label: "card"),
        KnownEvent(identity: "default:open:card", category: Category.default_, action: Action.open, label: "card"),
        KnownEvent(identity: "home:open:card", category: Category.home, action: Action.open, label: "card"),
    ]

    public static func log(category: Category, action: Action, label: String? = nil, properties: [String: Any] = [:]) {
        Analytics.shared.log(category: category.rawValue, action: action.rawValue, label: label, properties: properties)
    }
}
