// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: legacy (named). Regenerate with `tripl codegen`.

/// The `legacy` events (named): one case per planned event, carrying
/// exactly the values the plan leaves open. Send one with `LegacyTracking.track(_:)`.
public enum LegacyEvent: Sendable {
    /// `Home Screen View`
    case homeScreenView(HomeScreenView)
    /// `checkout:start`
    @available(*, deprecated, message: "Deprecated in the tracking plan.")
    case checkoutStart
    /// `promo_sheet_${sheet_id}_shown`
    case promoSheetSheetIdShown(PromoSheetSheetIdShown)
    /// `trial_started`
    case trialStarted(TrialStarted)

    public enum Platform: String, CaseIterable, Sendable {
        case android = "android"
        case ios = "ios"
    }

    public enum SheetId: String, CaseIterable, Sendable {
        case spring = "spring"
        case summer = "summer"
    }

    public struct HomeScreenView: Sendable {
        public let mode: String
        public let isFirst: Bool?
        public let platform: Platform?

        public init(mode: String, isFirst: Bool? = nil, platform: Platform? = nil) {
            self.mode = mode
            self.isFirst = isFirst
            self.platform = platform
        }

        public var name: String { "Home Screen View" }

        public var properties: [String: Any] {
            var properties: [String: Any] = [:]
            properties["mode"] = mode
            if let isFirst { properties["is_first"] = isFirst }
            if let platform { properties["platform"] = platform.rawValue }
            return properties
        }
    }

    public struct PromoSheetSheetIdShown: Sendable {
        public let sheetId: SheetId
        public let isFirst: Bool?
        public let platform: Platform?

        public init(sheetId: SheetId, isFirst: Bool? = nil, platform: Platform? = nil) {
            self.sheetId = sheetId
            self.isFirst = isFirst
            self.platform = platform
        }

        public var name: String { "promo_sheet_\(sheetId.rawValue)_shown" }

        public var properties: [String: Any] {
            var properties: [String: Any] = [:]
            properties["mode"] = "promo_\(sheetId.rawValue)"
            if let isFirst { properties["is_first"] = isFirst }
            if let platform { properties["platform"] = platform.rawValue }
            return properties
        }
    }

    public struct TrialStarted: Sendable {
        public let isFirst: Bool?
        public let platform: Platform?

        public init(isFirst: Bool? = nil, platform: Platform? = nil) {
            self.isFirst = isFirst
            self.platform = platform
        }

        public var name: String { "trial_started" }

        public var properties: [String: Any] {
            var properties: [String: Any] = [:]
            properties["mode"] = "trial"
            if let isFirst { properties["is_first"] = isFirst }
            if let platform { properties["platform"] = platform.rawValue }
            return properties
        }
    }

    /// The event's name, exactly as the plan spells it.
    public var name: String { (self as any LegacyEventResolving).resolvedName }

    public var properties: [String: Any] { (self as any LegacyEventResolving).resolvedProperties }
}

/// Resolves every case — deprecated ones included — without a deprecation warning at
/// the switch: the switches live in deprecated members, reached through this protocol's
/// non-deprecated requirements, so warnings-as-errors builds still compile.
private protocol LegacyEventResolving {
    var resolvedName: String { get }
    var resolvedProperties: [String: Any] { get }
}

extension LegacyEvent: LegacyEventResolving {
    @available(*, deprecated, message: "Internal: use `name`.")
    fileprivate var resolvedName: String {
        switch self {
        case .homeScreenView(let event): return event.name
        case .checkoutStart: return "checkout:start"
        case .promoSheetSheetIdShown(let event): return event.name
        case .trialStarted(let event): return event.name
        }
    }

    @available(*, deprecated, message: "Internal: use `properties`.")
    fileprivate var resolvedProperties: [String: Any] {
        switch self {
        case .homeScreenView(let event): return event.properties
        case .checkoutStart: return ["is_first": true, "mode": "checkout", "platform": "ios"]
        case .promoSheetSheetIdShown(let event): return event.properties
        case .trialStarted(let event): return event.properties
        }
    }
}

public enum LegacyTracking {
    public static func track(_ event: LegacyEvent) {
        Analytics.shared.logEvent(event.name, parameters: event.properties)
    }
}
