// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: screen (screen_view). Regenerate with `tripl codegen`.

/// Typed screen views for the `screen` event type (screen_view): the plan's
/// screen types (and ids, where it has them), and the wrapper's call narrowed to them.
public enum ScreenTracking {
    public enum ScreenType: String, CaseIterable, Sendable {
        case checkoutStart = "Checkout Start"
        case homeView = "HomeView"
    }

    public enum ScreenId: String, CaseIterable, Sendable {
        case checkoutStart = "checkout:start"
        case home = "home"
    }

    public struct KnownEvent: Sendable {
        public let identity: String
        public let type: ScreenType
    }

    /// Every planned screen view, checked by the compiler against the enums above.
    public static let knownEvents: [KnownEvent] = [
        KnownEvent(identity: "Checkout Start", type: ScreenType.checkoutStart),
        KnownEvent(identity: "HomeView", type: ScreenType.homeView),
    ]

    public static func track(type: ScreenType, id: ScreenId? = nil, properties: [String: Any] = [:]) {
        TriplTracking.send(eventType: "screen", name: type.rawValue, fields: ["type": type.rawValue, "id": id?.rawValue], properties: properties)
    }
}
