// Generated by tripl codegen — do not edit.
// Plan: project demo, branch main, plan 5e0d4c3b2a19.
// Event type: sd (self_describing). Regenerate with `tripl codegen`.

/// A `sd` event (self_describing): one type per schema, carrying exactly the
/// values the plan leaves open. Send one with `SdTracking.track(_:)`.
public protocol SdEvent: Sendable {
    /// The event's identity, exactly as the plan spells it.
    var name: String { get }
    /// The schema URI the event is sent with.
    var schema: String { get }
    var data: [String: Any] { get }
}

public enum SdTracking {
    /// `iglu:com.example/checkout_started/jsonschema/1-0-0`
    @available(*, deprecated, message: "Deprecated in the tracking plan.")
    public struct CheckoutStartedV1_0_0: SdEvent {
        public let sku: String
        public let price: Double?

        public init(sku: String, price: Double? = nil) {
            self.sku = sku
            self.price = price
        }

        public var name: String { "iglu:com.example/checkout_started/jsonschema/1-0-0" }
        public var schema: String { "iglu:com.example/checkout_started/jsonschema/1-0-0" }

        public var data: [String: Any] {
            var properties: [String: Any] = [:]
            properties["sku"] = sku
            if let price { properties["price"] = price }
            return properties
        }
    }

    /// `iglu:com.example/checkout_started/jsonschema/2-0-0`
    public struct CheckoutStartedV2_0_0: SdEvent {
        public let sku: String
        public let price: Double?

        public init(sku: String, price: Double? = nil) {
            self.sku = sku
            self.price = price
        }

        public var name: String { "iglu:com.example/checkout_started/jsonschema/2-0-0" }
        public var schema: String { "iglu:com.example/checkout_started/jsonschema/2-0-0" }

        public var data: [String: Any] {
            var properties: [String: Any] = [:]
            properties["sku"] = sku
            if let price { properties["price"] = price }
            return properties
        }
    }

    /// `iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0`
    public struct PromoSheetViewed: SdEvent {

        public init() {
        }

        public var name: String { "iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0" }
        public var schema: String { "iglu:com.example/promo_sheet_viewed/jsonschema/1-0-0" }

        public var data: [String: Any] {
            var properties: [String: Any] = [:]
            properties["price"] = 4.5
            properties["sku"] = "none"
            return properties
        }
    }

    public static func track(_ event: some SdEvent) {
        TriplTracking.send(eventType: "sd", name: event.schema, fields: [:], properties: event.data)
    }
}
