// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: app (named). Regenerate with `tripl codegen`.

package com.example.acme

/** The `app` event names, exactly as the plan spells them. */
object AcmeAppEventNames {
    const val CHECKOUT_STARTED = "checkout_started"
    @Deprecated("Deprecated in the tracking plan.")
    const val CLASS = "class"
    const val PAYWALL_SHOWN = "paywall_shown"
    fun promoPromoCodeApplied(promoCode: String): String = "promo_${promoCode}_applied"
}

/** The `app` property keys. */
object AcmeAppEventKeys {
    const val IS_TRIAL = "is_trial"
    const val PLAN_TIER = "plan_tier"
    const val SOURCE = "source"
}
