// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

package com.example.acme

/** The plan's values for `action` (se). */
object AcmeAction {
    const val Close = "close"
    const val Open = "open"
    const val Show = "show"
    const val Tap = "tap"
    const val View = "view"
}
