// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: screen (screen_view). Regenerate with `tripl codegen`.

package com.example.acme

/** The planned `screen` screens: a (type, id) pair the plan does not list does not compile. */
enum class AcmeScreen(val type: String, val id: String?) {
    CHECKOUT_CART("checkout", "cart"),
    CHECKOUT_CONFIRM("checkout", "confirm"),
    HOME("home", "main"),
    PAYWALL_ANNUAL("paywall", "annual"),
    PAYWALL_MONTHLY("paywall", "monthly"),
    SETTINGS("settings", null);
}

object AcmeScreens {
    fun screen(screen: AcmeScreen) {
        AcmeTracker.trackScreen(type = screen.type, id = screen.id)
    }
}
