// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

package com.example.acme

/** The plan's values for `label` (se). */
object AcmeLabel {
    const val _1stCard = "1st_card"
    const val Default = "default"
    const val Offer = "offer"
    const val PayButton = "pay_button"
    const val Paywall = "paywall"
    const val PromoSheet = "promo-sheet"
    const val PromoSheet2 = "promo_sheet"
}
