// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

package com.example.acme

/**
 * Builds a `se` event as the team's own AcmeEvent, to be handed
 * on; pass the constants of AcmeCategory, AcmeAction, AcmeLabel, AcmeProperty.
 */
object AcmeStructured {
    fun event(
        category: String,
        action: String,
        label: String? = null,
        property: String? = null,
        value: Double? = null
    ): AcmeEvent = AcmeEvent(
        category = category,
        action = action,
        label = label,
        property = property,
        value = value
    )
}
