// Generated by tripl codegen — do not edit.
// Plan: project acme, branch main, plan a1b2c3d4e5f6.
// Event type: se (structured). Regenerate with `tripl codegen`.

package com.example.acme

/** The plan's values for `category` (se). */
object AcmeCategory {
    const val Checkout = "checkout"
    const val Home = "home"
    const val Paywall = "paywall"
}
