"""The template context for one event type in one language: shared parts, and the
field-enum styles (``structured``, ``screen_view``).

The generated API is per event-type STYLE, never a function per event:

``structured`` / ``screen_view``
    One enum per plan field (its cases are the plan's values for that field),
    and ONE function whose signature is the team's wrapper with the argument
    types narrowed: ``log(category: Category, action: Action, label: String,
    properties:)``. A ``knownEvents`` constant lists every planned combination,
    type-checked by the compiler, for tooling and tests.

The contexts carry both the pieces (``params``, ``enums`` …) and ready-made
spellings (``signature``, ``forward``) so a custom template can reshape the
file without re-deriving the language rules. Every key a built-in template
uses is documented in ``website/docs`` via the CLI README.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from tripl_cli.check.config import (
    NAME,
    NAME_IGLU,
    PRESET_STYLES,
    PROPERTIES,
    STYLE_NAMED,
    STYLE_SCREEN_VIEW,
    STYLE_STRUCTURED,
    CodegenSpec,
    EventTypeSpec,
)
from tripl_cli.codegen import naming
from tripl_cli.codegen.calls import Arg, args_of, callee, function_name, render_call
from tripl_cli.codegen.languages import Dialect, comment
from tripl_cli.codegen.model import (
    RULE_KEY_OR_TOKEN,
    TOKEN,
    CodegenModel,
    EventTypeModel,
    FieldModel,
    whole_token,
)
from tripl_cli.codegen.naming import KOTLIN, SWIFT, TS, Namer
from tripl_cli.codegen.value_types import STRING, EnumRegistry, ValueType, scalar_type

MARKER = "Generated by tripl codegen"
# Stands in for the plan hash while files are rendered without one (an export
# from a server that sends no ``plan_hash``); ``generate`` replaces it with a
# sha256 over everything the run generated.
PLAN_HASH_PLACEHOLDER = "\x00plan-hash\x00"
DESTINATION_FUNCTION = {SWIFT: "TriplTracking.send", KOTLIN: "TriplTracking.send", TS: "triplSend"}
SHARED_TYPES = frozenset({"TriplDestination", "TriplTracking"})
_SCREEN_VIEW_TYPES = {"type": "ScreenType", "id": "ScreenId", "name": "ScreenName"}


@dataclass(frozen=True)
class Target:
    """One event type to generate: its config, its plan, and the run's facts."""

    spec: EventTypeSpec
    codegen: CodegenSpec
    event_type: EventTypeModel
    model: CodegenModel
    project: str
    kotlin_package: str | None = None

    @property
    def style(self) -> str:
        if self.codegen.style is not None:
            return self.codegen.style
        for preset in self.spec.presets:
            if preset in PRESET_STYLES:
                return PRESET_STYLES[preset]
        return STYLE_STRUCTURED if self.event_type.rule_keys else STYLE_NAMED

    def type_override(self, key: str) -> str | None:
        return self.codegen.type_names.get(key)


def plan_line_prefix(project: str) -> str:
    """The start of a generated file's second line: it names the project the file is of."""
    return f"// Plan: project {comment(project)}, "


def header_lines(target: Target | None, model: CodegenModel, project: str) -> list[str]:
    """The header names the plan's CONTENT hash, not its revision: a new revision
    with the same content must not make every committed file drift."""
    branch = model.branch or "main"
    plan_hash = comment(model.plan_hash) if model.plan_hash else PLAN_HASH_PLACEHOLDER
    lines = [
        f"// {MARKER} — do not edit.",
        f"{plan_line_prefix(project)}branch {comment(branch)}, plan {plan_hash}.",
    ]
    if target is not None:
        lines.append(
            f"// Event type: {comment(target.event_type.name)} ({target.style}). "
            "Regenerate with `tripl codegen`."
        )
    else:
        lines.append("// Regenerate with `tripl codegen`.")
    return lines


def base_context(target: Target, dialect: Dialect) -> dict[str, Any]:
    transport = target.codegen.transport.get(dialect.name)
    imports = []
    if transport is not None and transport.import_line and dialect.name != SWIFT:
        imports.append({"line": transport.import_line})
    if dialect.name == TS:
        shared = []
        if target.style not in (STYLE_STRUCTURED, STYLE_SCREEN_VIEW):
            shared.append("triplInterpolate")
        if transport is None:
            shared.append("triplSend")
        if shared:
            imports.append({"line": f"import {{ {', '.join(shared)} }} from './triplTransport';"})
    return {
        "header": "\n".join(header_lines(target, target.model, target.project)),
        "kotlin_package": target.kotlin_package if dialect.name == KOTLIN else None,
        "imports": imports,
        "has_imports": bool(imports),
        "event_type": {
            "raw": comment(target.event_type.name),
            "literal": dialect.literal(target.event_type.name),
            "display_name": comment(target.event_type.display_name or target.event_type.name),
        },
        "style": target.style,
        "uses_destination": transport is None,
    }


def field_target(target: Target, raw: str | None) -> str | None:
    """A call target -> the plan field it addresses, or the reserved target itself."""
    if raw is None or raw in (NAME, NAME_IGLU, PROPERTIES):
        return raw
    if raw.startswith("field:"):
        return raw[len("field:") :]
    return target.spec.resolve_target(raw)


def interpolation(
    dialect: Dialect, template: str, resolve: Mapping[str, str], *, braces: bool
) -> str:
    """A plan template as a string expression; ``resolve`` maps key -> text expression.

    ``braces`` reads ``{key}`` (a name rule; a ``${token}`` in it stays text),
    otherwise ``${key}`` (a plan token). A key with no expression stays in the
    output as the literal text it was.
    """
    pattern = RULE_KEY_OR_TOKEN if braces else TOKEN
    parts: list[tuple[bool, str]] = []
    position = 0
    for match in pattern.finditer(template):
        key = match.group(1)
        if key is None:
            continue  # a `${token}` inside a name rule: literal text
        if match.start() > position:
            parts.append((False, template[position : match.start()]))
        expression = resolve.get(key)
        parts.append((True, expression) if expression is not None else (False, match.group(0)))
        position = match.end()
    if position < len(template) or not parts:
        parts.append((False, template[position:]))
    return dialect.interpolate(parts)


# --- structured / screen_view --------------------------------------------------
def _field_values(target: Target, field: FieldModel) -> tuple[set[str], bool]:
    """``(values, free)``: the plan's values for ``field`` across the type's events."""
    if field.values is not None:
        return set(field.values), not field.values
    values: set[str] = set()
    free = False
    for event in target.event_type.events:
        raw = event.value_of(field.name)
        if raw is None:
            continue
        if not TOKEN.search(raw):
            values.add(raw)
            continue
        variable = whole_token(raw)
        allowed = target.model.allowed_for(event, variable) if variable is not None else None
        if allowed is None:
            free = True
        else:
            values.update(allowed)
    return values, free or not values


def _enum_base(target: Target, field: str, dialect: Dialect) -> str:
    override = target.type_override(field)
    if override is not None:
        return override
    if target.style == STYLE_SCREEN_VIEW and field in _SCREEN_VIEW_TYPES:
        return _SCREEN_VIEW_TYPES[field]
    return naming.type_name(field, dialect.name)


def _structured_type(
    target: Target, field: FieldModel, dialect: Dialect, registry: EnumRegistry
) -> ValueType:
    values, free = _field_values(target, field)
    if free:
        return scalar_type(field.type) if field.values is None else STRING
    return registry.enum(_enum_base(target, field.name, dialect), values)


@dataclass(frozen=True)
class _Param:
    ident: str
    label: str | None
    target: str
    type: str
    optional: bool
    value_type: ValueType | None
    # A non-optional parameter the caller may omit: ``properties`` defaults to an
    # empty map, so a wrapper whose own parameter is non-optional still compiles.
    default: str | None = None


def _signature(dialect: Dialect, params: list[_Param]) -> str:
    parts: list[str] = []
    for number, param in enumerate(params):
        if dialect.name == SWIFT:
            head = param.ident
            if param.label is None:
                head = f"_ {param.ident}"
            elif param.label != param.ident:
                head = f"{param.label} {param.ident}"
            default = " = nil" if param.optional else ""
            if param.default is not None:
                default = f" = {param.default}"
            type_name = f"{param.type}?" if param.optional else param.type
            parts.append(f"{head}: {type_name}{default}")
        elif dialect.name == KOTLIN:
            default = " = null" if param.optional else ""
            if param.default is not None:
                default = f" = {param.default}"
            type_name = f"{param.type}?" if param.optional else param.type
            parts.append(f"{param.ident}: {type_name}{default}")
        else:
            tail_optional = all(
                later.optional or later.default is not None for later in params[number:]
            )
            if param.default is not None:
                parts.append(f"{param.ident}: {param.type} = {param.default}")
            elif param.optional and tail_optional:
                parts.append(f"{param.ident}?: {param.type}")
            elif param.optional:
                parts.append(f"{param.ident}: {param.type} | undefined")
            else:
                parts.append(f"{param.ident}: {param.type}")
    return ", ".join(parts)


def _text_expression(dialect: Dialect, param: _Param) -> str:
    """A NON-optional string expression for ``param`` (empty when absent)."""
    value_type = param.value_type or STRING
    text = value_type.text(dialect, param.ident, optional=param.optional)
    if not param.optional:
        return text
    if dialect.name == SWIFT:
        return f'({text} ?? "")'
    if dialect.name == KOTLIN:
        return f'({text} ?: "")'
    return f"({text} ?? '')"


def structured_context(target: Target, dialect: Dialect) -> dict[str, Any]:
    event_type = target.event_type
    lang = dialect.name
    namespace = target.type_override("namespace") or naming.type_name(
        event_type.name + " tracking", lang
    )
    types = Namer({namespace, "KnownEvent", *SHARED_TYPES})
    registry = EnumRegistry(dialect, types)
    field_types = {
        field.name: _structured_type(target, field, dialect, registry)
        for field in event_type.fields
    }
    transport = target.codegen.transport.get(lang)
    default = [
        Arg(naming.member(field.name, lang) if lang != TS else None, field.name)
        for field in event_type.fields
    ] + [Arg(PROPERTIES if lang != TS else None, PROPERTIES)]
    args, object_arg = args_of(transport, default)
    idents = Namer(naming.KEYWORDS[lang])
    params: list[_Param] = []
    by_target: dict[str, _Param] = {}
    for arg in args:
        plan_target = field_target(target, arg.target)
        if plan_target is None or plan_target in (NAME, NAME_IGLU) or plan_target in by_target:
            continue
        if plan_target == PROPERTIES:
            param = _Param(
                idents.take("properties"),
                arg.label if lang == SWIFT else None,
                PROPERTIES,
                dialect.properties_type,
                False,
                None,
                dialect.empty_map,
            )
        else:
            field = event_type.field(plan_target)
            value_type = field_types.get(plan_target, STRING)
            param = _Param(
                idents.take(naming.member(plan_target, lang)),
                arg.label if lang == SWIFT else None,
                plan_target,
                value_type.type_name(dialect),
                field is None or not field.required,
                value_type,
            )
        by_target[plan_target] = param
        params.append(param)
    name_expression = dialect.null
    if event_type.name_rule:
        resolve = {key: _text_expression(dialect, param) for key, param in by_target.items()}
        name_expression = interpolation(dialect, event_type.name_rule, resolve, braces=True)

    def expression_for(raw: str | None) -> str:
        plan_target = field_target(target, raw)
        if plan_target is None:
            return dialect.null
        if plan_target in (NAME, NAME_IGLU):
            return name_expression
        param = by_target[plan_target]
        if param.value_type is None:
            return param.ident
        return param.value_type.text(dialect, param.ident, optional=param.optional)

    if transport is not None:
        where = f"event_types.{event_type.name}.codegen.transport.{lang}"
        keep_labels = lang != TS or object_arg is not None
        arguments = [
            (arg.label if keep_labels else None, expression_for(arg.target)) for arg in args
        ]
        forward = render_call(dialect, callee(transport, where), arguments, object_arg)
    else:
        forward = _destination_call(dialect, target, name_expression, params)
    function = target.type_override("function") or function_name(transport, "track")
    context = base_context(target, dialect)
    context.update(
        {
            "namespace": namespace,
            "enums": registry.context(),
            "function": {
                "name": function,
                "signature": _signature(dialect, params),
                "forward": forward,
                "params": [
                    {
                        "ident": p.ident,
                        "type": p.type,
                        "optional": p.optional,
                        "default": p.default,
                    }
                    for p in params
                ],
            },
            "known": _known_events(target, dialect, field_types),
        }
    )
    return context


def _destination_call(
    dialect: Dialect, target: Target, name_expression: str, params: list[_Param]
) -> str:
    entries = [
        (dialect.literal(param.target), _field_text(dialect, param))
        for param in params
        if param.target != PROPERTIES
    ]
    properties = next(
        (param.ident for param in params if param.target == PROPERTIES), dialect.empty_map
    )
    event_type = dialect.literal(target.event_type.name)
    if dialect.name == SWIFT:
        fields = "[" + ", ".join(f"{k}: {v}" for k, v in entries) + "]" if entries else "[:]"
        return (
            f"{DESTINATION_FUNCTION[SWIFT]}(eventType: {event_type}, name: {name_expression}, "
            f"fields: {fields}, properties: {properties})"
        )
    if dialect.name == KOTLIN:
        fields = "mapOf(" + ", ".join(f"{k} to {v}" for k, v in entries) + ")"
        return (
            f"{DESTINATION_FUNCTION[KOTLIN]}(eventType = {event_type}, name = {name_expression}, "
            f"fields = {fields}, properties = {properties})"
        )
    fields = "{ " + ", ".join(f"{k}: {v}" for k, v in entries) + " }" if entries else "{}"
    return f"{DESTINATION_FUNCTION[TS]}({event_type}, {name_expression}, {fields}, {properties})"


def _field_text(dialect: Dialect, param: _Param) -> str:
    value_type = param.value_type or STRING
    return value_type.text(dialect, param.ident, optional=param.optional)


def _known_events(
    target: Target, dialect: Dialect, field_types: Mapping[str, ValueType]
) -> dict[str, Any] | None:
    event_type = target.event_type
    keys = [key for key in event_type.rule_keys if event_type.field(key) is not None]
    if not keys:
        keys = [field.name for field in event_type.fields]
    if not keys:
        return None
    lang = dialect.name
    idents = Namer({"identity", *naming.KEYWORDS[lang]})
    members = {key: idents.take(naming.member(key, lang)) for key in keys}
    events = []
    for event in event_type.events:
        values: list[tuple[str, str]] = []
        for key in keys:
            raw = event.value_of(key)
            if raw is None or TOKEN.search(raw):
                break
            literal = field_types.get(key, STRING).literal(dialect, raw)
            if literal is None:
                break
            values.append((members[key], literal))
        else:
            assign = " = " if lang == KOTLIN else ": "
            pairs = [("identity", dialect.literal(event.identity)), *values]
            events.append(
                {
                    "args": ", ".join(f"{name}{assign}{value}" for name, value in pairs),
                    "identity": comment(event.identity),
                    "deprecated": event.deprecated,
                }
            )
    if not events:
        return None
    fields = [
        {"ident": members[key], "type": field_types.get(key, STRING).type_name(dialect)}
        for key in keys
    ]
    return {"fields": fields, "events": events}
