"""Writing generated files, or comparing them with what is on disk (``--check``).

A file is "ours" when its first line carries ``context.MARKER`` AND its second
names the same project, and it is in a language this run generates. Only ours
are ever deleted: a generated file whose event type left the config (or the
plan) is STALE, removed on a write and reported as drift under ``--check``.
Anything else in an output directory — a hand-written helper next to the
generated code, another project's generated files, a language this run was
told to skip (``--lang swift`` never touches ``.kt``) — is never touched.

Bytes are compared and written exactly: UTF-8, ``\\n`` line endings on every
platform, so a Windows checkout and a Linux CI runner agree on "unchanged".
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from tripl_cli.codegen.context import MARKER, plan_line_prefix
from tripl_cli.codegen.generate import GeneratedFile
from tripl_cli.codegen.languages import DIALECTS
from tripl_cli.errors import TriplError


@dataclass
class SyncResult:
    created: list[Path] = field(default_factory=list)
    changed: list[Path] = field(default_factory=list)
    unchanged: list[Path] = field(default_factory=list)
    stale: list[Path] = field(default_factory=list)

    @property
    def drifted(self) -> bool:
        return bool(self.created or self.changed or self.stale)


def _read(path: Path) -> bytes | None:
    try:
        return path.read_bytes()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise TriplError(f"cannot read {path}: {exc}") from None


def is_generated(path: Path, project: str | None = None) -> bool:
    """Generated by tripl codegen — and, with ``project``, for that project."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            first, second = handle.readline(), handle.readline()
    except OSError:
        return False
    if MARKER not in first:
        return False
    return project is None or second.startswith(plan_line_prefix(project))


def stale_files(files: Sequence[GeneratedFile], project: str) -> list[Path]:
    """Our files in the output directories that this run no longer produces."""
    produced = {item.path.resolve() for item in files}
    # Per directory, only the languages this run writes THERE.
    extensions: dict[Path, set[str]] = {}
    for item in files:
        extensions.setdefault(item.path.parent, set()).add("." + DIALECTS[item.language].extension)
    stale: list[Path] = []
    for directory in sorted(extensions):
        if not directory.is_dir():
            continue
        for candidate in sorted(directory.iterdir()):
            if candidate.suffix not in extensions[directory] or not candidate.is_file():
                continue
            if candidate.resolve() in produced:
                continue
            if is_generated(candidate, project):
                stale.append(candidate)
    return stale


def sync(files: Sequence[GeneratedFile], *, check: bool, project: str) -> SyncResult:
    result = SyncResult()
    for item in files:
        wanted = item.content.encode("utf-8")
        current = _read(item.path)
        if current == wanted:
            result.unchanged.append(item.path)
            continue
        (result.created if current is None else result.changed).append(item.path)
        if not check:
            try:
                item.path.parent.mkdir(parents=True, exist_ok=True)
                item.path.write_bytes(wanted)
            except OSError as exc:
                raise TriplError(f"cannot write {item.path}: {exc}") from None
    result.stale = stale_files(files, project)
    if not check:
        for path in result.stale:
            try:
                path.unlink()
            except OSError as exc:
                raise TriplError(f"cannot remove stale {path}: {exc}") from None
    return result
